# (PART) Inception {-}

# Introduction to inception {-}

- make a good plan, and adjust throughout the project. 

work in progress

optimal survey design, reduces error 

make a plan to survey quality maximization, e.g minimize TSE while keeping the other dimensions acceptable, Biemer 2010 

- less can be more. A reduced questionnaire doing the key variable sof interest well can e  better than trying to do many and ending up doing them worse. Fewer things to train, understand and monitor. Likewise, a smaller sample with a higher response rate might be more valuable. 

- if there are too few resources available to do the survey well, try to either obtain more or question the feasibility of the survey. 

- plan holistically. Efficiently allocating resources to maximize survey quality requires to look at the big picture and treat each activity as part of the whole that they are as each activity affects others. Some activities might be cut that have little or no effect on survey quality, to save resources for others where it matters. E.g. to afford a longer interviewer training one might reduce field team size and extend the duration of field work, if there are no time constraints or seasonality issues.

- good plan: to achieve timeliness. Overlap activities that can be done together. For example, with CAPi survey and a fixed data output format you can start working on the data documentation, cleaning, or even to some extend the analysis while the survey is still in the field. Do not overlap activities that depend on each other. For example, translation of instruments should only start once the instrument and CAPI coding have been finalised. Keepign track of change in overlapping activities is cumbersome, and leads in most cases to mistakes and survey erros. 

- make gantt of key activities and draft timeline

- list of depending activities, e.g. only do training after instrument has been finished.


- Draw upon the experiences from other surveys in the same context, subject or modality. While every survey tends to be a different, the effect can often be generalised. In other words, what worked in one survey, often works in another survey with similar parameters. Make sure to have enough survey expereince in your team!

# Schedule

Make sure your schedule keeps into consideration and works around the following **forseeable** events:

- Public holidays and vacations that might limit field workers or respondents availability or affect results, e.g. increased household expenses in the week of Christmas or Eid.   

- Seasonality effects, that need to be catered for, such as such as harvest periods or that might affect your results.  

- Weather patters such as rainy seasons that might limit field work operations. 

Allow margin to cater for **unforseeable events** that might affect your survey, such as abnormal weather events, unexpected field worker attrition, strikes or demonstrations


# Formulation

work in progress

# Personel

work in progress

- remove field team effects. As shown in Chapter LINK INTERVIEWER, interviewers, supervisors, data monitors or any other level can have huge effects on the TSE. As an example, interviewers of one supervisor who thoroughly back-checks interviews with respondents will be careful to not under report household members, parcels etc, while those of a more lenient supervisor may notice that they can get away with under reporting.

that is  centraize processes, so they can e monitored and streamlined, to remove supervisor, or data editor effects. 
Examples are:
    - instead of reviewing interview files in field y each supervisor, let them do only the basic completion checks, and do in depth review and feedback of the interviewed by a central team of editors, that regularly debrief, receie 
    
- rotate staff, so that not always the same person enters data , reviews interviews, provides feedback to one interviewer only. 
- review the work of each data monitor, editor, superviisor, 


- for data entry, rotate data entry staff

# Contracting considerations

work in progress
