
# (PART) Survey Quality {-}

# Introduction to Survey Quality 

Sample surveys are a crucial data source for official statistics, impact evaluations and social economic research. Survey data informs public policy and other important decisions. Quality in surveys is paramount for good policies and sound decisions and should be the aspiration of all survey practitioners. In Part I of this book we summarize key frameworks used by survey methodologists and national statistical offices (NSOs) to conceptualize and maximize quality in surveys. Skip this part if you are not interested in the theoretical background of survey quality. We will link back to the concepts throughout the remainder of the book, so you can read only relevant parts.

Quality can be defined as *fitness for use*. For something to be fit to use it must be *free from deficiencies* and *respond to the users' needs*  [@Juran1980]. In a survey context, freedom from deficiencies translates to the requirement of survey data to be *accurate* to allow inferences about the target population. In other words, a survey statistics must accurately describe the population for it to have any value. Responsiveness to users' needs translates into aspects such as timeliness, usability and completeness that are important to the *user of survey data*. Even the most accurate data can be unusable if it is outdated, poorly documented or not rich enough for the intended analysis. Which user attributes matter, depend on survey. As we can already see, survey quality is a complex, multidimensional concept.

In Chapter \@ref(tse) we look at *Total Survey Error* (TSE). It is the dominant framework used by survey methodologists to maximize the accuracy of survey estimates within survey constraints. We describe different sources of survey error and provide real-world examples for each error source. We explain how error affects survey statistics and how the TSE can be used as a planning criterion to reduce overall error in survey estimates.

In Chapter \@ref(tsq) we introduce the notion of *Total Survey Quality* (TSQ) that combines survey accuracy with user-specific dimensions of quality. The concept is the basis of  multi-dimensional survey quality frameworks that are now used by many national statistical offices as a planning and evaluation tool. We present a general strategy how TSQ can be used to design surveys that maximizes survey quality.

The chapters are based on the articles by @Biemer2010 and @Groves2010, and the books by @Biemer2003 and @Weisberg2005. They are good starting points for readers who are interested in learning more about the theory of survey quality.

