
# Planning and Preparing


Fieldwork training should be planned well in advance and be well prepared prior to the start of field  

It consist of the interviewer training, separate training for supervisors, data monitors or other roles.  

The chapter presents recommendations for survey designers, survey managers and trainers. 
Survey designers, take note of the chapters duration, training size and trainees, as they are budget and timeline relevant. Survey managers and trainers might chapters schedule, content and preparation mgiht eb relevant to allow for a solid preparation fof the training.

## Training size 

LSMS strongly recommends to train more trainees than are ultimately needed as fieldworkers, i.e. as interviewers, supervisors, data monitors or other roles. This allows for a [competency-based selection](#assessment-selection) of fieldworkers at the end of the training. Training more people than needed also compensates any attrition of trainees during the training and builds a reserve of already trained persons that can be brought up to speed relatively quickly during fieldwork, should fieldworkers need to be replaced.

Train __at least 40% more fieldworkers__ than are required if you are working with unknown trainees, a new implementing partner or in a new context. For example, train at least 56 people if you are aiming for 40 fieldworkers. Even if some drop out before the end of the training, this still allows you to not select some of the trainees that are not up to the task. You can reduce the excess to 20% if you are working with experienced teams who you have worked with before and if you are expecting few trainees to drop out during the training. Training less than 20% additional people is not recommended as it prohibits a meaningful fieldworker selection process. 

Often, some trainees will drop out during the training, particularly after day 1 or 2 once there is a clearer understanding of the required effort. Mitigate early trainee attrition by keeping on standby some of the applicants that have not been invited to the training, so they can quickly replace any trainees that have not come back. You might have to bring them up to speed in extra hours and ask them to independently learn already covered material to catch up. It is not advised to bring in additional trainees after day 3, as they will have fallen behind too far. 

:::: {.warning data-latex=""}
In some surveys, there have been walk-outs of trainees, often towards the end of the training, in which trainees collectively refuse to continue the training or fieldwork unless their demands are met. Usually, there is no time or budget to repeat the training with other trainees, leaving survey management in a very weak bargaining position and putting the survey itself at risk. Avoid walk-outs by setting fair [fieldworker terms and conditions](Fieldworker terms), making them clear to trainees prior to the training, and asking them to agree by signing a copy of the terms and conditions. 
::::

In many circumstances it is beneficial to select supervisors, data monitors and any other fieldwork roles from the pool of trainees based on their performance and capabilities observed during the training (see [Assessment & Selection](#assessment-selection)). If any of the fieldwork roles are predetermined, the designated persons should participate in the fieldwork training without being counted towards the trainees excess (and demonstrate full understanding of the trained material).  

Keep the number of trainees as small as possible, __ideally below 50 trainees__ (around 36 fieldworkers) and maximum around 70 trainees (around 50 fieldworkers). Learning outcomes quickly decrease with increasing class size, as each trainee receives less supervision and personal feedback and as it is more difficult for trainers to keep track of trainees' performance. If possible, adjust the fieldwork plan, so that fewer fieldworkers work over a longer period of time. See Chapter [Fieldworker Recruitment](#fieldworker-Recruitment) for other benefits of having a smaller field team.  

If it is necessary to train more than 70 trainees (e.g. surveys in large country or with large sample) or a centralized training is not possible (e.g. different languages or geographically dispersed sample), it might be adequate or imperative to split fieldworker training into separate rooms or even locations. In those instances it is paramount to __standardize the training__ between different rooms/locations as much as possible in order to minimize the "[training effect](#impacterror)". 

This requires the training to be largely guided by standardized and extremely well-prepared training materials, and effective communication between the training rooms/locations, so that all trainees benefit from relevant feedback, comments, questions, etc. raised in one room/location. on top of that, there must be sufficient capable trainers who have received a comprehensive *Training of Trainers* (ToT). the ToT can be a dedicated exercise or integrated as an explicit outcome of the pilot training. Several scenarios are possible if a large number of fieldworkers need to be trained:

1. __Partitioned training__. This is the first best option to train larger class sizes (70-150 trainees) that can be trained centrally. Split the class into groups of manageable size around 15-20 trainees and assign dedicated trainers to each group. Train all modules that are sensitive to class size in the groups, including the questionnaire reading and practicing. Trainers must keep notes of any additional clarifications they provided, questions they received or feedback they gave. Hold daily plenary sessions with the entire class in which feedback is given based on the notes from individual groups. Modules that are less size-sensitive, such as the opening module or fieldwork logistics can be trained in the full class. 

1. __Parallel rooms__. Some surveys have split trainees into groups that are independently trained at the same location. Each group has a "resident" trainer, responsible for the training in this group. Other trainers responsible for certain modules rotate between groups. Compared to the partitioned training described above, it is harder in this approach to harmonize training between groups. It is only desirable if significant input from expert trainers is needed.

1. __Consecutive training__. Different groups of interviewers are trained one after the other. A core set of trainers repeats the same training for each group, providing consistency between the groups. Since each group should start fieldwork immediately after their training, this approach only works if a staggered field start is possible (e.g. if field work is sufficiently long). Additional trainers should attend the training for each group, so that they can supervise the field start of one group while the core trainers move on to train the next one.    

1. __Parallel locations__. It is not recommended to simultaneously train in multiple locations, as it is difficult to harmonize fieldwork training between different locations. If unavoidable, it is essential for trainers to keep good notes, frequently communicate and debrief with trainers from other locations. 


## Trainers 

The success of a fieldwork training hinges upon having enough and competent trainers.

Conducting a fieldwork training is a substantial amount of work! Doing it well even more so. [Prepare the training well](#trainingpreparation) to avoid significant reductions in quality or trainers getting overwhelmed. Make provisions for enough trainers so they can conduct the training well. For every room, there needs to be __a minimum of two active trainers__ at any point in time, one to lead the training and another one to support the class or do any of the supporting activities that need to happen in parallel, such as updating manuals, compiling feedback, creating practicing scenarios, etc. Larger classes require more trainers as supervision and supporting activities increase. Ideally, there should be one active trainer for every 15-20 trainees.

Trainers must have availability to actively engage in the training most of the time. Avoid the situation where trainers are physically present, but either are in meetings, stare at their laptops or do other tasks unrelated to the survey. Cater for more trainers if trainers have ongoing other responsibilities outside of the training (which is often the case).

All trainers must have:

- A good understanding about the survey in general 
- A detailed understanding of the questionnaires, definitions, protocols, manual, CAPI, etc. Ideally, they have been involved in the survey design process, participated in the pre-test or pilot and will be involved in managing and monitoring fieldwork. 
- A general understanding of the survey subject, e.g. the regional agricultural systems for an agricultural survey. 
- Good facilitation skills and the ability to lead and manage all components of the training. 

Collectively, the trainers of one room should also have: 

- A good understanding of the indicators construction, the intended data use or analysis.  
- Subject and context expertise, e.g. know in detail the local circumstances of child education, nutrition and health for a survey on early child development. 
- Experience in implementing the survey type and implementing surveys in the context 
- Experience in conducting fieldworker training 
- Speak the trainees' language. Do not train in a language the trainees are not fluent in. If some trainers (usually the survey designers or analysts) do not speak the training language, other trainers can translate for them. 

Particularly in surveys with limited pre-testing and piloting, often mismatches between the survey design and field reality are uncovered during the training and adjustments need to be made quickly. For example, a locally practiced exchange labor system might not be picked up accurately in the questionnaire. Trainers need the above expertise and experience to be able to identify those issues and take decisions that are analytically correct, in-line with the survey design and make sense in the local context. 

There is a tendency to send junior analysts or PhD students without sufficient survey or context experience to conduct the interviewer training. This can work, as long as other experienced trainers are present, but quickly leads to quality issues if they are the main training lead.  

Similarly, handing over a sample and questionnaire to a survey firm and letting them implement the training without monitoring them closely is usually a bad idea. Firms commonly lack the analytical background, do not know about the details of the survey design, are differently motivated, and might not have the capacity to conduct the training to the required standard. If working with a new firm, it is recommended to send your own trainers to be present at the training, support if necessary and ensure the training meets the quality standards described here.

Some surveys advocate for subject experts to facilitate some of the modules. Unfortunately, they often have their own agenda and priorities and come with a varying capacity to conduct effective fieldworker training, making it sometimes a waste of time (e.g. long, theoretical presentations on details that are largely irrelevant for interviewers). If external subject experts will lead parts of your training, make sure they fully understand the relevant parts of the questionnaire and what knowledge they need to transmit to trainees. Prior to the training, discuss the scope of their engagement and review their contributions, such as presentations. Subject experts can also be given a backstopping role to answer any questions on the subject and contribute to relevvant disucssions.

## Content

To equip trainees with all the knowledge and skills necessary to do a successful job as interviewers, training must go beyond a simple discussion of the questionnaire and cover the following components:

- CAPI: Try to focus on the interviewer perspective and limit it to the functionality that is relevant for the interviewer in this study. Keep the theory to a limit and practice as much as possible. It is better to gradually introduce new functionality as needed rather than have an extensive theoretical session at the beginning.

- Questionnaire. Question types, questionnaire formatting, navigation, routing, understand all questions and answer options. How to administer each question and section. Underlying key concepts and definitions.

- Practicing. Repeated practicing, alone, in groups and with respondents is required, so that interviewers are fully familiar with the questionnaire content, know how to navigate it in the CAPI tool, can administer it correctly and get exposure to real respondents and scenarios during the training.
 
- Protocols. Exercises such as capacity tests, anthropometrics, plot measurement or behavioral games require strict adherence to protocols for comparable measurements. Trainees must fully internalize protocols and practice them until behavior across the entire field team has been homogenized.

- Assignment management. How to receive household assignments. How to find and locate households. When and how often to revisit. Replacement protocols. How to plan interviews and manage your workload.

- Interviewing skills. How to introduce yourself and the study as well as convince respondents to participate. How (not) to ask questions. How to not lead questions. How to probe, inquire, get clarifications. How to control the interview. Manage respondents time. How to deal with impatient respondents.

- Post-interview skills. How to check for completion. How to address in-consistencies. How to leave comments. How and when to submit files. How to receive feedback and respond to inquiries on submitted interviews. How to (not) make corrections. How to ask questions.

- A full dress rehearsal at the end of the training that mimics real field conditions and asks interviewers to track and interview households. 


## Timing & Duration 

 

Schedule at least 1 full week (6 working days) of interviewer training per 1-1.5 hr questionnaire time. To some readers, this might sound long, and many survey firms, especially when conducting opinion surveys will suggest much shorter training times. In most cases it is impossible to train the field teams to a higher standard in a shorter amount of time. Do not save on training days, unless you are very confident that you all trainees will have fully internalized the required material and be able to perform well as field workers.  

Socio-economic questionnaires are long and complex. They require interviews to understand a large number of questions  and to fully internalize complex concepts and definitions such as employment types, or land management systems, etc., and to correctly apply those in the field. On top of that, interviewers need to learn and practice a range of skills such as convincing respondents to participate or continue, troubleshooting inconsistencies, responding to feedback from supervisors, etc.    

In many surveys, trainees are not ready to go to the field at the end of the training and the training needs to be extended last minute. If extensions have not been budgeted for, firms will have to cut corners elsewhere to compensate for increased costs. Avoid this by setting out with a realistic training duration and putting contingencies for potential extensions into the budget and timelines. 



anthro 5-6 days
questionnaire reading + practicing

Fieldwork training should be held __just prior to the start of fieldwork__, with a maximum of 1-3 days between training and fieldwork to allow for admin, rest day and travel to the field. The shorter the break, the better interviewers remember the trained material and can solidify it by practicing it immediately in the field. 

If the break is longer than a few days, the risk of interviewers forgetting details and  developing idiosyncratic behavior increases. Conduct a short refresher training just prior to the field start to refresh key points of the trained material. If the field start is being delayed further, a longer refresher training or complete retraining will be necessary.

## Schedule

Prepare a solid schedule and try to stick to it during the training. Track your progress on an on-going basis during the training. Make adjustments and organize extensions as soon as you notice that you are falling behind or need more time, before logistics make this impossible. If training progresses faster than anticipated, use the time for additional practicing. Only shorten the training if you are certain that the trainees are fully ready for the field.    

A few consideration for drawing up a functional training schedule: 

1. __Do not exceed 6-7 hours of training time per day__ and give frequent breaks, without the breaks taking over the day. For example, a morning session from 8.30 AM - 12 PM, and an afternoon session from 1 PM - 5 PM, each with a flexible 15 minutes break. Allow for enough time for trainers to debrief and prepare for the following days. 

1. __Frequently change training modality__, e.g. by putting practicing sessions between questionnaire reading sessions. Avoid as much as possible long sessions of only questionnaire content, PowerPoint, theory only. 

1. Trainee attention levels tend to be lower after lunch and in the afternoon. During these times,  schedule hands-on, more interactive sessions that require greater engagement from trainees, such as practicing or quizzes. 

1. __Be efficient__. Only train content that interviewers need to know. Allocate time on topics proportionate to the direct importance for the interviewers. 

1. __Keep it together__. Train material only in context, once it is needed and can be practiced. Example, practice “How to introduce and ask for participation” the day before the first field practice or agricultural key definitions when going through the respective questionnaire. 

1. __Stay flexible__. You could draw up a very detailed plan with exact timings for each session, but in reality the timing of sessions tends to shift a bit during the training. Use the schedule as guidance to track progress, but stay flexible to allow sufficient time to address issues, retrain topics, or dive into more detail as needed. 

1. __Allocate time generously__. It is better to finish training early one day rather than keeping trainees until late, being behind schedule or rushing content. If you are falling behind schedule during the training, extend the training as early as possible so all logistical arrangements can be adjusted. 

1. __From theory to practice__. During the first days, focus on the questionnaire content and conduct frequent on-site practices. In the latter half, schedule field practices, interviewing skills, feedback sessions. 

1. __Specialize fieldworkers__. If your survey requires a lot of different questionnaires (e.g. in school surveys) or special tasks to be conducted (e.g. medical samples), it is often too much material for all interviewers to learn everything. Instead, divide the field teams into different roles that each completes a different set of questionnaires/tasks. During the training, those questionnaires/tasks can be trained in parallel sessions, allowing for more in-depth training. 

expand on this one: 
long 
Parallel training only for dedicated other roles, supervisors and monitors need to attend everything. 


1. Train field supervisors data monitors or similar roles outside of the hours of the interviewer training, so they can attend the interviewer training in full and know everything interviewers are supposed to (not) do. Typical time slots are towards the end of the training once supervisors have been selected during the late afternoon or evenings, or during administrative days or rest days.    

1. Schedule classroom days after field days so that you can hold in-class debrief sessions with the big screen.  

1. __Rest days__. For training lasting over one week make sure to schedule one or two rest days per week. Trainees and trainers need regular breaks for good learning outcomes.  

Below is an example training and piloting schedule for a 1hr-long questionnaire collecting information on agriculture and a few other socio-economic indicators. The schedule allows for practicing of learned material, changes modality frequently, and includes daily quizzes and feedback sessions.

```{r training_schedule, echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE}
library(kableExtra)
options(kableExtra.html.bsTable = T)
options(knitr.kable.NA = '')
library(readxl)

schedule <- read_xlsx("resources/training_schedule.xlsx", col_types = c("numeric","text","text","text","text"))
days <- rle(schedule$Day)$lengths
names(days) <- paste("Day",rle(schedule$Day)$values)

schedule[,2:4] %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(index = days, label_row_css = "background-color: #666; color: #fff;")
```

You can download the sample schedule as an Excel from [here](resources/training_schedule.xlsx).

<!-- should we add popover messages on why modules are where they are? -->

MICS train for 25 working days. 

efficiency, good organisation can have a good learning outcomes in shorter time. 

too long, fatigue and forget 


parallel sessions for measurers, specialized tasks. can start from days one if no overlap in tasks, little awareness and roels are already clear e.g. if trained nurses are needed. Otehrwise, often useful to identify specialised trainees during training, after one has workked with trainees for a few days, to get to know their capabilities and personality. E.g. measurers need ot eb good with kids and practice, good number rading skills, but do not need to understand all concepts in a long hh questionnaire. Allows to trainees that perfroma ccordingly in the training. 



## Location

Fieldwork training is best held in a location that:

- __Has sufficient logistically capacity__: Is easy to reach for trainers and trainees, has a suitable training venue, sufficient accommodation and food options, good network coverage, print shops, etc. 

- __facilitates field testing__: Is close to communities that are similar to but outside of the sample. If the survey is limited to a specific region or area, it is best to conduct the fieldwork training there.

- __facilitates field start__: Allows field teams to start field work shortly after the training and trainers to supervise the first few days of field work. 

Find a training venue with a big hall large enough to comfortably fit the entire team (or multiple halls if parallel sessions are held) and space to breakout into smaller teams for group exercises, such as a garden, hallways, the cantine or additional rooms. It is crucial that there is __good internet connectivity__ at the venue, either through on-site Wifi, or general network connectivity. 

The venue should be either able to accommodate trainees and cater for food, or be easily accessible and close to restaurants or eateries. It should be quiet and free from distractions. Good venues tend to be hotels or conference centers with garden or open space. Avoid universities, schools, towns halls or other places that are busy and become easily unavailable. 

Book the venue early. Check for availability, in case the training needs to be extended on short notice. 


## Preparation {#trainingpreparation}

Avoid wasting precious training time by preparing everything that can be prepared prior to fieldwork training. This includes: 


- Make sure they have learned about the survey details and terms before the training, including the areas to be visited, the population to be interviewed, the transport and lodging arrangements during field work, the length of field work, the interviewer selection process, their remuneration package, insurance, contract details etc. Provide them in written form and have each trainee sign it prior to the training. 

- Schedule any contract signing for a time or day that does not interfere with the training. Pulling trainees in and out during a session reduces its effectiveness.  

- __Projector with a BIG screen__. The projected content must be visible and legible to all trainees. You should be able to connect a PC and tablet/phone to the projector. Ideally, it should be possible to quickly link trainees' devices to the projector, to facilitate exercises and practicing. Test the set-up prior to the start of the training.

- __Stable internet connection for all devices__. Trainees have to sync their devices several times per day. Usually, the WIFI connection of the training venue is not sufficient to connect all devices at the same time. Often, additional mobile network routers or WIFI hotspots are required. One option is to already provide the internet connection that is planned for field work, e.g. the dongles, mobile phone routers or sim cards.  

- Electricity and extension cords to charge all devices.  

- __Food and refreshments for the breaks__. If food is provided by the venue, make sure it is ready in time for the break. If trainees eat out for lunch, set reasonable break times that allow trainees to finish lunch and to be back in time. Incentivize punctuality, e.g. those coming back late from the break have to sing a song.  

referral forms for anemia or severe undernutrition. 

- equipment if needed, measuring boards, scales GPS equipment

- __One tablet/phone per trainee__. It is crucial for all trainees to learn how to navigate the questionnaire CAPI and use the device. If you do not have enough devices (since there are more trainees than interviewers) borrow devices or ask some trainees to use their private devices. Devices must meet the minimum specifications for the CAPI software (see [here](https://docs.mysurvey.solutions/faq/what-tablets-should-i-buy-/){target="_blank"} for Survey Solutions) and have the correct CAPI version installed. Consider using an app blocker to allow using specific apps only. Add shortcut/icons on the main screen for CAPI, the softcopy of the manual, the calculator or any other relevant app. 

- __Fully set-up CAPI software__. For Survey Solutions this includes the installation of Survey Solutions on a server, interviewer accounts for each trainee, questionnaires imported to the server and assignments made. For training, often open assignments with infinite quantity (-1) are useful. Create several assignments with different scenarios if the questionnaire includes substantial pre-loading (e.g. household rosters in a panel survey). 

- printed questionnaires if needed. One at the beginning, and further throughout the training. additional copies of household memer roster, plot or parcel rosters etc, for practicing. 

- printer in venue good idea

- samples of documents or items that interviewers need to interpret, such as birth certificates, immunization cards, school timetables, anti-malaria medications, for hand-son practicing. 

- logistical tools such as household tracking lists, village maps, etc. community completion sheets

- __Finalized questionnaires__. The questionnaires should be reviewed, extensively pre-tested or piloted, translated and the translations verified. The CAPI version of the questionnaire should be extensively desk-tested and error free. Mistakes can cause significant issues or delays during the training. Provide printed copies of the paper questionnaire [if needed](#capi-use). 

- __Fieldworker manuals__. All manuals for interviewer, supervisor or other fieldworker roles have to be made available to trainees from the beginning of the training, so trainees can use them and get used to using them as a reference. [Modifications and additions](#questionnaire-content) should be made to the manuals during the training wherever it was unclear or incorrect. Either hand out a printed version of the manual at the beginning and a revised version at the end, or provide regularly updated soft copies in pdf to the trainees which they can look at on their devices (which tends to work very well). 

- __Facilitation material__. Microphones and speakers including batteries and fully tested, flip charts with non-permanent markers in multiple colors for drawings, name tags/stickers for all participants, printed attendance lists and feedback forms, for trainees notebooks, pens in 2 colors to allow  marking and clipboards, etc.

- Field work material: bag packs, rain coats, ID cards, battery packs 

- __Organize in-field practicing__. Select practice areas/communities well in advance. They must not be included in the sample. Make all necessary administrative arrangements such as getting permissions, introduction to village officials, etc. If necessary, arrange respondents for field practices, so trainees can spend more time practicing than looking for respondents to participate (don't do this in areas/communities for the final field test). Organize reliable transport for the trainees to travel to the field practice. Make sure the transport waits for the team, not the other way round.

- __Organize on-site practicing__. Arrange respondents for on-site practicing to visit the training venue, including transport, food/refreshment and remuneration.  

- __Logistical/administrative support__. Get a dedicated person to support with all the logistical and administrative work that has to be done during the training, e.g. setting up the venue, organizing transport, contacting local leaders, printing, purchasing equipment, signing field worker contracts, etc. If these activities have to be done by the trainers, they become a substantial distraction and can significantly affect training quality and pace.


## Notes:

MICS:"
Preparing for the training
Training should be planned well ahead of time. Before training the field staff, the following must be in place:

•	Other field procedure documents, such as the Cluster Control Sheets, necessary accounting documents, or any specific ethical guidelines , must also be prepared in advance.
•	Logistics for the fieldwork are key and should allow for the fieldwork to commence immediately after the training completes: Payments, accommodation, transport, insurance, etc. are among some of the absolutely key components to have established protocols for. It is well known that unless fieldwork payments are paid on time, the quality of the entire fieldwork is jeopardised.
•	Similarly, logistics for the training itself is key, including all monetary matters.
•	Identified and arranged locations/institutions and transportation for anthropometric training (pre-schools, day care centres, hospitals, etc.)
•	Prepared equipment, visuals, and tools for use in demonstrations during training and for practice and pilot. See appendix A for a typical list of materials.
•	Field equipment, i.e. tested tablets and accessories, anthropometry and water quality testing items, first aid kits, flashlights, rainboots, umbrellas, bags, caps, t-shirts, response cards with literacy sentences, smilies, etc., must all be available for distribution.
•	Agreed upon agenda and methodology – also for selection of field teams.
•	Secretariat support for the duration of the training.
"


