
# Conducting the Training

This chapter is targeting trainers and provides details on how to deliver an effective and efficient interviewer training that facilitates learning without overstretching survey resources. The chapter assumes in-person training as is the case for most surveys conducted with in person interviews. The first sub-chapter covers general considerations for the training. The remainder of the chapters is organised by training module. Each sub-chapter provides details on the rational, optimal timing and recommendations for the implementation of the respective module. See the [training schedule](#trainingschedule) in Chapter \@ref(planning-and-preparation) on how individual modules relate and are best combined.   

Prior to the start of fieldworker training, make sure everything is [fully set-up](#trainingpreparation).

## General considerations

Throughout the fieldworker training, consider the following points:  

- __Essentials only__. Only train fieldworkers on things that are relevant for them and that their respective role is required to do. For example, there is no need for interviewers to learn details about the survey analysis or Survey Solutions supervisor CAPI role.   

- __Confirm with designers/analysts__. The interpretation of a question or concept
must be aligned all the way from how it has been designed to how it is fielded. This is not always the case. Keep note of anything you are uncertain about or anything that is under-defined and run it by designers/analysts on a daily basis. Ask them to be on standby so you receive timely responses. Get back to the trainees once you have received the response. 

- __Eliminate language barriers__. Do not train in a language the trainees are not fluent in. If some trainers (usually the survey designers or analysts) do not speak the training language, use an interpreter or ask other trainers (e.g. fieldwork manager) to translate or reiterate their points in the training language.  

- __Support trainees__. Especially during the first few days, trainees often get lost in the CAPI or questionnaire and are unable to follow the sessions. Trainers who are not actively leading a session should walk around the class, check that trainees are in the right place and support those falling behind.

- __Probe for understanding__. It is wrong to assume things have been understood if you just ask “Any questions?” and there are none. There hardly ever are any. Probe using common examples or scenarios. Ask variations of your test questions. For example, think of working profiles/jobs that are typical in the surveyed population and probe trainees if these are wage employed or self-employed.   

- __Encourage questions__. From the beginning, make it clear to trainees that they should ask if they have ANY question, that it is better to ask than to remain with a doubt, and that there are no bad questions. Take questions seriously and address them. If trainees prefer not to ask in front of the class, they can raise their hand and be visited by a trainer. 

- __Involve trainees__. Asking frequent questions. Let trainees read aloud questions and manuals. Ask them to correct one another. Don’t always pick the most engaged trainees but try to involve everyone. Select a trainee using a [random name picker](https://wheelofnames.com){target="_blank"}, so it can be anybody’s turn to answer your questions at any moment. They make it fun if displayed in front of class. Alternatively, select the person that is closest to where a paper ball lands (that you or anyone throws over their back). Select one trainee for a couple of questions to speed up things. 

- __Get to know trainees__. Ask trainees to wear name tags during the first few days. Learn their names as quick ass possible. This makes the training more personal and helps trainers to better connect trainees' in-class performance with written tests or test interviews. 

- __Collect and react to feedback__. At the end of each day, use feedback forms to collect anonymous feedback from trainees on how clear different sessions or trainers were, topics they did not understand or questions they have. Review feedback forms prior to the next day and adjust your training schedule or methods if needed. ??KEVIN: provide feedback form example.   

- __Break up and mix groups__. If you start noticing groups of trainees sitting together who are not paying attention or are in the bottom end of performance, distribute them across the classroom. Ask low performers to sit next to high performers, so they can help when falling behind. 

- __Make it fun__! Maintain a general positive and fun attitude. Play fun and exciting [group games](https://www.sessionlab.com/blog/large-group-games-and-activities/#){target="_blank"}. The last person entering the venue late and unexcused can sing a song in front of the class (Youtube is full of Karaoke videos). Hold a end of training party. 

- __Use video & audio__. It can be a good way of demonstrating certain things like interviewing tequniques or special tasks to trainees, so they can see/hear what they should and should not do and learn from examples. Use existing material if good, or collect video/audio material during pre-test, pilots and field practices to demonstrate good and bad practices to the class. 

- __Stress importance__. Make it repeatedly clear to the trainees that it is important that they do a good job, that the survey result and ultimately policy and decisions depend on it. Give them a sense of purpose. Like any other human being, interviewers perform better at work if they care about what they do.

- __Trainees are responsible for their learning__. Make clear to trainees that it is up to them to ensure they have understood the covered material. they can read the manual, practice outside the class, learn from peers, ask questions, etc. to make sure they understand everything. There is a transparent and objective selection process at the end and they must pass it.

- __Set and enforce rules__. Trainees must attend all days and sign attendance every day. Ask trainees to be on time and respect training hours yourself by not running late or running over time.  No side conversations, no (excessive) use of cell phones. Enforce in a fun but serious way, e.g. anyone breaking rules can donate to the cookie char, has to hand in their cell phone, sing a song, etc.  

- __Zero tolerance for cheating__. Make it clear from the beginning that there will be serious consequences for anybody being caught intentionally making up data or purposefully breaking protocols (ideally being immediately dismissed). Also make clear that fieldworkers have nothing to fear as long as they follow what has been taught during training and check with supervisors or fieldwork managers if there are any situations they are unsure about. 

- __Daily trainer meeting__. Trainers should meet daily at the end of the day to compare notes, evaluate progress and trainee performance, review tests and class feedback and plan the following day(s). Include supervisors if they are pre-determined.

## Opening module

The opening module serves to introduce trainees to the survey and training. In many surveys, opening modules are unnecessarily long and involve too many people. Keep it as short as possible (1-2 hrs are enough) to be able to cover some content on the morning of the first day. Cover:

- __Opening speeches__. Try to keep speeches by officials or leaders as short as politically possible and avoid, if possible, the opening of the class to depend on officials, as they might be late.

- __Introduction to survey/organization__. Give a brief introduction of the survey, its objectives, the organization, the project/study, etc. Do not go into too much detail here and limit it to what is essential for fieldworkers to know. If needed, provide more details in the manual and refer trainees to it. 

- __Introduction of trainers and trainees__. All trainers and core survey team should briefly introduce themselves and their roles. Avoid introduction rounds for trainees if the class size is large, they are dull an ineffective. Play a fun ice breaker instead. Ask all trainees and trainers to write their name on a name tag and carry it during the training.

- __Training plan__. Run through the rough training schedule, daily working hours, explain need for punctuality, that there will be frequent test and evaluation of skills, that trainees are responsible for their learning, that all questions are encouraged, that there is zero tolerance for cheating, that trainees have to follow what is lerant here (and forget other surveys they have done if done differently).

- __Survey details and terms__. Run through the overall survey parameters and contract terms, including the selection process, their remuneration package, insurance coverage, areas to be visited, the length of field work, the transport and lodging arrangements during field work, expected effort, etc. Importantly, this should be a refresher, NOT be the first time trainees learn details about their pay, other terms or the field work. Make sure all trainees have understood and signed a copy of the general terms prior to the training.

- __Administrative/contractual matters__. If you need to address administrative or contractual matters with trainees, such as contracts signing, registering for insurance, signing out tablets, etc, try to do this as mcuh as possibel before the training start (e.g. from 8-10 AM), or in a dedicated slot during which trainers do not need to be present.   

 At the beginning, introduce the survey, sketch out the training and field work plan and set the training rules. Keep it short so you can focus on content during this day.

## CAPI use 

This chapter assumes Survey Solutions to be used, but the same principles apply to other CAPI packages. 

CAPI, as any other software, __is best learned by using it__. Covering all functionality in an long theoretical session tends to be very ineffective as any functionality that is not immediately put to practice by trainees is forgotten and needs to be retrained later in the training. It is more productive and a better use of time to initially only cover the asic functionality that is necessary to proceed with the training, and to gradually introduce additional functionality as required throughout the training. For example, trainees don't need to learn how rejected interviews work until they learn about post-interview activities in the latter part of the training.  

Limit the functionality you train to what is relevant from the perspective of an interviewer and what will be used in the actual survey. For example, trainees do not need to learn how the Supervisor interface works, what exactly happens at HQ, or how assignments work or what a Yes/No question type is if there is none in the questionnaire. 

The fewer slides you have in the CAPI training and the more demo and practice you do the better. Train functionality by demonstrating it on the big screen and asking trainees to follow on their own device. Make sure the class can follow and wait for those falling behind to catch up. Those lost should check with their neighbors or raise their hand, so one of the trainers can come to assist. For example, show on the big screen how to login to the Interviewer app. Wait until all trainees are logged in on their tablets. Show on the big screen where to find an assignment card, explain what it is and show how to create a file. Wait for everyone to have opened an interview file on their tablet, and so on. Clarify any questions or doubts trainees might have on the way. 

You can __train the questionnaire directly in CAPI__, without training it on paper first, if you are using Survey Solutions or another CAPI software that provides a good overview over the questionnaire, makes routing behavior clearly understandable and allows for free navigation between different parts of the questionnaire. Note, this is usually not the case for software showing one question per screen.

Training the questionnaire directly in CAPI has the advantages that trainees only need to learn the questionnaire in the format they will ultimately use in the field (e.g. no need to learn how skips work on paper). Trainees will also practice CAPI along the way, making them much earlier confident in using the CAPI version of the questionnaire and the CAPI software in general. New trainees do not notice any difference, and experienced trainees who are used to paper questionnaires usually stop missing them after a day or two. 

Train the basic CAPI functionality just before trainees need to use it for the first time. usually, around 1 hour is enough. If you are training the questionnaire on paper, train the CAPI basics just before trainees practice for the first time on the tablets, usually on the first or second day.  

If you are training the questionnaire directly on CAPI, introduce the CAPI basics just before starting with the questionnaire content, usually on the morning of the first day. 
For Survey Solutions, cover the following topics in the initial introduction: 

- A general overview, including how the Interviewer App and HQ server interact, what assignments and interview files are, what synchronizing does. Keep this part short.

- How to log-in to the Interviewer app. Make sure tablets and accounts have been set-up prior to the training. How to create an interview file from their assignment.  

- A general overview of the Interviewer App and how to navigate through the questionnaire.  

- The outline of a question, the question number, the question text (what to read and what not), the instructions, the answer options (different by type). 

- Question and section enablement. It is sufficient to work on the first section of the questionnaire.  

- The complete screen, marking an interview as complete. 

- The started and completed screen on the dashboard, reopening an interview file, discarding an interview file. 

Having completed the above steps, trainees should be able to follow in the questionnaire during the questionnaire content modules. The remaining CAPI functionality is best trained throughout the training when trainees need to use the functionality for the first time.

- During the questionnaire content modules, train the different question types, roster forms, static texts, sections and sub-sections as they come up, e.g. list questions in the household member module, yes/no questions in assets, etc. Trainees need to recognize and understand the difference between single select, multi-select, numeric, list and date questions, and understand the rosters. 

- Prior to practicing or the first [written tests](#written-tests) (if done in Survey Solutions), train how to synchronize to receive assignments, create new interview files, review interviews on the complete screen, marking them as complete and synchronize to send a file. Conducting the test on Survey Solutions tends to be useful, as trainees need to correclty synchronize to get the assignment and submit their test (send the completed interview file).

- Prior to group or field practicing, train how to add comments to questions and at synchronization, so that trainees can leave questions and comments directly in the interview files when practicing.  

- After field practicing or the final field test, train how to receive rejected interviews, respond to comments, and resubmit rejected interviews, so trainees can practice [post-interview activities](#post-interview-activities) using interview files they have created themselves.  

## Questionnaire content 


:::: {.warning data-latex=""}
A single, joint reading of a questionnaires is not sufficient for trainees to learn and understand the various concepts, definitions, and scenarios that are necessary to correctly administer a socio-economic questionnaire. Some implementing agencies, such as survey firms used to implementing opinion surveys, sometimes do not recognize the required effort and vastly underallocate training time for questionnaire content.
::::

Trainees must understand in detail the entire questionnaire(s), including the underlying definitions and concepts. Usually, this makes for a substantial amount of material to be covered, which if not trained well, can be quite dull and an ineffective use of time. Consider below points to make the questionnaire content modules interesting and effective: 

- __Avoid long content sessions__. Covering the content of an entire questionnaire usually takes many training days. Avoid training content for more than 2 hours at a time. Long content sessions tend to be an information overload for trainees and make it impossible for them to internalize the content. Instead, spread the content training over more days and let trainees [practice](#practicing) the newly trained material at least twice per day, e.g. after every long questionnaire section (or a few short ones).     

- __Less instructional, more interactive__. Avoid one-directional training methods where trainers give long presentations or read questions without really interacting with trainees. This tends to be a very ineffective way of getting across questionnaire content. Instead, involve the trainees as much as possible. For each question (or a few at a time), select one trainee to read aloud the question and any instructions, answer options or corresponding manual entry. Ask the trainee to explain in their own words what they have understood and how the question is to be administered. Make sure the rest of the class can hear them. Correct them if needed. Ask the rest of the class for input. Check if the trainee has understood by probing with an example. Give feedback on tone of voice and way of asking the question. Ask the trainee to read out the question again if needed. 

- __Explain the big picture__. At the beginning of each section (or part of the questionnaire if you have small sections), provide a brief general overview to the class, including the overall structure and routing behavior, things to be aware off, key concepts and definitions, the targeted respondent(s), etc. It is better to do this section by section (rather than once at the beginning of the training), so trainees can immediately see and later practice what has been trained, and can thus remember it more easily. 

- __Go into detail__. Many questions have to be covered in more depth for interviewer to be able to administer them correctly. This can include explanations on the underlying concepts and definitions, how to categorize responses into the given answer options, common scenarios that require further probing, what error messages mean, what conditions open the question, how the question relates to other questions, how to sense check responses, etc.

- __Make it tangible__. Definitions for survey concepts such as *household*, *wage employed*, *parcel*, etc. can be very theoretical and hard for trainees to translate into the real world. When training anything theoretical or abstract, always try to illustrate it with examples and scenarios that are common in the surveyed population to make it easier to understand for trainees. For example, to explain what is *wage-employed* and *self-employed*, list jobs or work profiles that are common and show which category they fall in.

- __Use the manual__. The [interviewert manual](#manual) should hold all conventions on how to correctly administer the questionnaire. It must be always up-to-date to be correct. Also, trainees must develop the habit of consulting the manual to get additional information or to clarify doubts, or it will never be used. Ask trainees to keep the manual open on paper or as soft copy on their device. After reading each question, ask trainees to check if there is a corresponding manual entry and to read it. One of the trainers should update the manual directly during the training if the entry is unclear or insufficient. Ask for input from the class if needed and confirm with them if the updated entry is clear. Distribute updated soft copies of the manual to the team every morning/evening.

- __Use your time effectively__. There will always be a few rare cases in the population that the questionnaire does not cover well. Trainees love pointing those out, e.g. _“But what if ….?”_ If these scenarios are frequent they might require you to update the questionnaire or manual. If not, tell trainees to leave comments in the questionnaire if the situation arises in the field, and move on with the training, so that you have enough time to focus on the important parts. If longer discussions arise in class, clarify and stop the discussion. If you are not sure how to answer, get back to them the next day after having read up or consulted with the design team.  

- __Multi-language questionnaires__. If the questionnaire has been translated into other languages, display the questionnaire in the training language on the big screen and ask each trainee to follow the questionnaire on their tablet in the local language they are most likely to use. For each question, ask it to be read in the training and local languages. This serves to verify the translation and to familiarize trainees with the questionnaire in the local language. 

- __CAPI__. If training the questionnaires directly in CAPI (recommended), show and explain any new relevant CAPI functionality as you work your way through the questionnaire. On the big screen, demonstrate how the questionnaire should be filled in, how different question types function (e.g. text questions with patterns, search in combo box, etc.), highlight instructions or other parts that are not meant to be read out, what responses trigger what enablement or validation conditions, the overall organisation of a section and how to navigate it, etc. Ask trainees to follow on their tabets.    

- __Demonstrate__. Show how questions or (parts of) sections should be administered by demonstrating the part of the interview in front of class, either as trainer yourself, or by asking experienced trainees to act as respondent and interviewer. This is particularly useful for complex modules or parts that require inquiring, e.g. probing for the age of household members, a child nutrition module, parcel sketch, etc. Trainees can follow and record the responses in their tablet. Give immediate feedback, highlight any mistakes or parts done well, and provide additional information if necessary.     

- __Update the questionnaire & CAPI__. Depending on the level of pre-testing, piloting and subsequent change, the questionnaire, CAPI and translations may still contain issues that are uncovered during the questionnaire content training. Ideally, trainers not actively leading the training can make immediate corrections, as it tends to be less time consuming and allows corrected versions to be used sooner during the training. Be consistent and follow updating protocols when making changes, e.g. update the live version of the paper questionnaire, the CAPI and the translation sheet. Do NOT simply update the questionnaire on CAPI or local language only, as this will lead to inconsistencies, mistakes and survey error. Ask the class for inputs if useful, e.g. how to phrase a question, or what answer categories exists. If there are many corrections, ask a dedicated person in order to not slow down the training.  



## Practicing

Trainees should frequently practice learnt material. Daily group practice and front-of-class interviews towards the beginning of the fieldworker training are effective ways for trainees to learn and solidify newly covered parts of the questionnaires and to break-up the monotony of questionnaire content training. Practicing with respondents on-site or in the field towards the latter half of the training exposes trainees to real-world scenarios and respondents, and prepares them for fieldwork. Each practicing modality serves a different purpose. It is not recommended to use them interchangeably, but to combine them throughout the course of the training.

### Group practice 

Towards the beginning of the training, while new questionnaire content is being learnt, frequent practice is important for trainees to familiarize themselves with the questionnaire, learn how to adminster the questions and practice the use of CAPI. Good ways of practicing during this phase are *group practice* or *front-of-class interviews*. 

Hold __practice sessions on every day__ that new theoretical content has been introduced, so trainees can put it to practice and internalize it better. Do not wait to practice until the questionnaire has been covered fully or until the end of the day if a lot of material has been covered. Instead hold 2-4 practice sessions per day at natural breaks (e.g. between sections) to practice the material/sections covered just prior. The change of training modality helps to maintain attention levels. Immediately repeating material helps trainees to understand and internalize it and helps to uncover remaining doubts. Practicing more frequently becomes unfeasible as each practice requires time to set–up.   

Group exercise can be effective for small groups of 2-8 trainees. Change group composition between exercises. When allocating trainees to groups, mix trainees and break up clusters that formed in the class, so that low/high performers and those paying more/less attention are distributed. Try to be efficient and not to waste time when creating groups. For pairs, ask trainees to practice with their peers in the row in front/behind. For groups, work out the number of groups *n* needed, and repeatedly count loud from 1 to *n*, pointing at a trainee for each number. Each number corresponds to a group, and each number/group can meet in a different point of the training venue, e.g. *“All number 4s, meet at the blackboard. All number 3, at the door...”*. 

Ask groups to practice the questionnaire sections that have been covered since the last practicing session. If there is time, groups can also practice all sections learned to date. They should not work through parts of the questionnaire that have not been covered yet.    

Give scenarios for trainees to ensure they practice scenarios that are likely to occur in the local context and cover all parts of the questionnaire. For example, when practicing the labor section, ask to complete it for an employed individual, self-employed, supporting family worker, etc. 

??NOTE, add example scenario box?

Within each group, one trainee should read and ask the questions while another one answers them. After a few questions/sections the roles should be rotated, so each trainee had the opportunity to act as an interviewer or respondent. All trainees in a group should follow on their own tablet and record the answers, which at the end should be identical for all trainees within a group in theory. Ask groups to submit their interviews after the feedback session to motivate them to get it correct. 

Feedback after practicing sessions tends to be thin. Asking the class if there were any doubts, questions or comments often results in general silence. In order to receive better feedback, ask groups to actively come up with feedback points, note them on a sheet of paper including the trainees’ names, and to submit those to the trainers at the end of the exercise. Feedback points can be any question or doubt they have about questionnaire, definitions, scenarios, etc or any mistakes they have found. You can set a minimum number of feedback points, e.g. 3 during the beginning of the training when things are not clear yet, and 1 towards the end of the training.  

Trainers should observe groups that have been allocated to them, correct mistakes and help struggling trainees on the spot, but also take note of the issues they observed for the feedback session. They should consider any issues, including the way questions were read or answered, the intonation, misunderstandings, questionnaire navigation, CAPI use, etc. While observing, trainers should also rate and record trainees' [skill levels](#rate-skills) and give individual feedback where necessary. 

Debrief with the entire class immediately after the exercise. Ask groups for their written feedback and discuss and answer their questions in class involving input from other teams/trainees. Ask trainers to provide the feedback from their observations, explaining what was done wrongly and also how to do it correctly. Ask trainees who have been observed to do something well to demonstrate to the class (e.g. how to explain a concept/question), so that all can learn from good examples.

### Front-of-class interview

Asking trainees to conduct (parts of) an interview in front of the class is a good way to demonstrate how interviews should (not) be conducted and evaluate trainee skills. It also shows if the class is able to spot any mistakes done and allows trainers to provide feedback on interviewing to the entire class. It is a good means of practicing after a good part of the questionnaire has been covered, and before practicing with respondents on-site. This exercise tends to take much longer than a normal interview, so either practice only parts of the questionnaire, or schedule several hours.

Project one tablet to the big screen on which the responses for the interview will be recorded. It is best to not chnage the tablet during the exercise.  

For front-of-class interviews, select one trainee to come to the front and act as interviewer in a mini-role play. Select one at random that has not yet been to the front. It usually makes sense to rotate trainees after a few questions (e.g. 5-10), so more trainees get the opportunity to practice in the front and make the exercise less monotonous. Ask the next trainee to already prepare and wait in front in order, so the rotation of trainees does not take up too much time.

Select someone to act as respondent throughout the whole exercise. This can be another trainee, or preferably one of the trainers or a real respondent. Using a trainer has the benefit that they can direct the interview with their answer and probe if some scenarios are understood. Using real respondents exposes the trainees to scenarios and respondents that are closer to what they expect to find in the field. For real respondents, hire a person that is similar to the surveyed population to visit the training venue for the afternoon/morning.

Ask the interviewing trainee to administer the questions as if they were in a real interview and to record the responses on the tablet that is projected onto the big screen. The respondent should give normal responses with some difficult scenarios.

Ask the rest of the class to follow the interview and raise their hand if they have a question or comment about the interview in front. As a trainer, pause the interview and give immediate feedback if the interviewer could have done better. Consider any aspects of the interview process, including tone of voice, reading speed, way of inquiring, etc. Ask the class for input, e.g. if they spotted the mistake or have any ideas how to do it better. Ask the trainee to repeat the question taking the input on-board. Also highlight things they have done well, so it is clear to the class that this is the way the questionnaire should be administered.

All trainees should record all answers in their own tablet. At the end, their interview files should look the same. Asking the class to submit their interview files after the exercise is a good way to encourage them to follow closely and make sure they record everything.  

### On-site respondents  

Practicing with real respondents on-site is a great way to give trainees more and early exposure to real-world scenarios, while keeping the logistical effort and required training time low. Trainees learn how to apply the theory they learnt and how to handle real respondents. Another advantage of this modality is that trainers can observe all or most trainees conducting interviews, which is nearly impossible during field practicing when they are scattered across many homes.

The best timing for an on-site practice is after the questionnaire has been covered completely and be practiced in group practicing, and prior to the first field test.  

Hire a group of respondents to visit the training venue or some other convenient location to be interviewed there. Depending on the number of trainees, some 5-10 respondents are usually enough. They should be similar to respondents in the surveyed population, e.g. cultivate land and keep livestock in agricultural surveys, or have jobs or small businesses in labor force surveys. Make sure to compensate respondents adequately, pay for the transport and refreshments or to invite them to the training lunch should it be provided. 

For the practicing, group trainees into as many groups as you have respondents, ideally not more then 4-6 interviewers per respondent. Each group should conduct a full interview with the respondent. Each trainee should follow on their own device and record answers, and they should take turns in asking the questions, e.g. a few questions or a section at a time. Groups should support each other if individuals fall behind, have questions or make mistakes. Ask groups to submit their interviews after the feedback session to motivate them to get it correct.  

If there is sufficient time, groups can switch respondents and conduct a second or third interview.  

Collect feedback, observe and debrief as described above for [group practice](#group-practice).

### Field practice 

The purpose of field practice is for trainees to get first experience in implementing the questionnaire with real respondents. There is no need to completely mimic field conditions as one does in dress rehearsals. Rather, aim to maximize the number of interviews each trainee can conduct and the number of respondents and scenarios they are exposed to. Prepare field practice well, observe trainees and collect good feedback to make it a success.  

:::: { .warning  data-latex=""}
Field practice often is implemented inefficiently with a lot of time being wasted on logistics that could have been prepared in advance: Teams waiting for transport, community introduction, looking for respondents, etc. It is not uncommon that during a whole day of field practicing, trainees only get to practice for 1 hour or could not practice at all as they did not find any respondent. Prepare well, so trainees can practice interviewing, not waiting.  
::::

Field practice sessions should be held after the questionnaire has been trained and practiced in class, and before the final dress rehearsal at the end of the training. Often it also makes sense to conduct it prior to sessions on household tracking, receiving rejecting interviews, logistics etc, so that content is broken down more and the field test can focus on the understanding and implementation of the questionnaire only. If the questionnaire is really long, e.g. a LSMS-ISA style questionnaire with long household and agricultural questionnaires, it can be beneficial to conduct more frequent field practices for different parts of the questionnaire. 

try to be efficient when conducting field practices. If relatively short or only parts of a questionnaire are tested, often half-day field practices are be sufficient to give some exposure to trainees and identify sufficient issues to be addressed prior to the next field practice. Since it is usually difficult to conduct class room training after the team has come back from the field, it is often helpful to conduct the field practice in the afternoon, so you can use the morning. 

Visit communities that are not too far from the training venue and large enough to have enough respondents for all trainees. Communities should have similar characteristics to the surveyed communities, but be outside of the sample. Contact or visit the communities the day prior to the field practice, do the community introduction and arrange for respondents at the time of your expected arrival, e.g. with the help of a community leader. Compensating respondents for their participation often helps with their availability and willingness to participate and is totally fine during field practicing. Again, the aim is for trainees to practice the questionnaire as much as possible with respondents. 

Try to minimize other logistical issues that could cause delays. Make sure all tablets are fully charged, synchronized and have battery packs available if needed. Arrange for food and drinks for trainees in the field or ask them to bring it. Make sure your transport arrives on time, knows the way and does not need to stop for petrol. Try to arrive early in communities, as respondents tend to become unavailable during lunch hours. 

Group trainees in pairs of two, trying to take skill levels into account and pairing high performers with low performers. Allocate each pair with a respondent. Agree on a meeting place for trainees to return to and a time by when they need to be back latest. Ideally, there is time for more than one interview per pair.  

Similar to the on-site group practices, trainees should take turns interviewing the respondent and both record all answers and submit the interview file at the end of the day. Ask them to write down any issues they experience while they conduct the interview. Working in pairs, one of them can take notes while the other one is interviewing. For each interview, each pair should list at least one question or doubt they had, and something about their interview or respondent that was noteworthy and is useful to share with the class.  

Try to observe as many of the pairs as possible, help and correct where necessary, mark their skills (LINK), and note down any issues you have observed as general feedback for the class. Focus on trainees that are borderline of being selected or that have not been marked yet.  

Collect as much feedback as possible from trainees __before__ you leave the community. It becomes much harder later and the quality of the feedback decreases rapidly. As pairs of trainees arrive back at the meeting place, ask for their written notes, debrief quickly with each pair, clarify any issues they had, and record general feedback for the class. 

:::: { .warning  data-latex=""}
Often trainers assume that the questionnaire is working well and that interviewers are able to administer it correctly because they did not report any issues during feedback sessions. This assumption is wrong. Many issues cannot be identified by interviewers, are forgotten or not reported. Those reported are biased towards trainee’s concerns, e.g. they are quick to report something that caused extra effort from their side. Trainers must observe interviews being conducted and compile their own feedback. To receive meaningful feedback from trainees, trainees must note down issues or questions as they experience them and must be debriefed shortly after conducting interviews.
::::

After each field test, hold a general debrief session with the entire class in which you respond to the written feedback from the team, answer any questions, and provide feedback from your observations. This might involve short retraining of concepts or questions that have been ill understood, practicing or role plays. Clarify all issues prior to the next field test. It is normal for quite a few things to go wrong in the first field test and to improve quickly.   

Sometimes, you can debrief to some extent directly in the field in an empty classroom, a community center, the shadow of a big tree, etc. This way interviews are still fresh in everyone's head and there is no need to go back to the classroom after the transport back from the field. If you are required to debrief the same day in the classroom, make sure to leave the field in time and to allow for a long break, as everyone tends to be really tired after field practicing, especially after the transport back.  

Design your training schedule such that field practicing days are followed by classroom days, so you can have a detailed debrief session in the classroom with the big screen and other all required facilities.  



## Interviewing techniques 

In addition to understanding the questionnaire content, interviewers must master a range of interviewing techniques that are crucial to collect good quality data. Some examples are:  

- __Introduction and interview request__: Being able to convince respondents to participate in the survey is key to keep unit non-response error low, particularly in urban areas or other settings with high refusal rates.

- __Interview continuation__: Being able to keep respondents engaged in lengthy interviews and stop them from prematurely ending the interview is important to minimize item non-response and measurement error.

- __Inquiring__: Respondents often do not understand or misinterpret a question, give incomplete answers, respond *"I don't know"* or do not want to disclose some information. Interviewers need to be able to get respondents to answer all questions in a neutral and non-leading manner. 

- __Controlling interviews__: Respondents sometimes digress, give lengthy explanations, or talk about other things. Interviewers need to be able to lead the conversation in a pleasant and courteous manner to maintain the respondent's cooperation. 

Unfortunately, these interviewing techniques are rarely trained. Instead it is assumed that interviewers automatically know them or will learn them over the course of the survey. In reality, while some interviewers are experienced or naturally good at it, many others struggle or resort to undesirable practices such as making wrong promises to obtain consent or leading responses. This can exacerbate interviewer effects and lead to high levels of measurement error and unit and item non-response. Teaching trainees that are not good a task the skills of those that are mitigates these effects, e.g. see @Groves2001.

Teaching interviewing techniques goes beyond theory. All features of communication are relevant for the interaction between interviewers and respondents, including the choice of words, tone of voice, volume, as well as attitude, facial expressions or gestures. To learn a technique, trainees have to see and hear what they should and shouldn't do, and learn from good examples. To be able to put techniques into use, trainees need to repeatedly practice and receive feedback until they are able to (re)act correctly and quickly.. 

Which interviewing techniques are best trained depend on the survey. Interviewers can face different challenges in the field. For example, refusals may be rare in a household survey, but very frequent in a enterprise survey, requiring dedicated training on how to address them. In addition, best practices often are sensitive to the culture and context, e.g. how to inquire if respondents are hesitant to disclose their income. Therefore, the training agenda on interviewing techniques usually needs to be tailored to each survey.

### Identify challenges and responses

To establish which interviewing techniques are most relevant for the survey and should be trained, first compile a list of the key challenges that interviewers are expected to face in the field and need to be prepared for. Focus on those that are most common and have the biggest effect on survey error. Consider any response, concern or action by the respondent or any other situation that can negatively affect data quality if interviewers do not apply the right technique. Examples are:

- respondents refusing an interview stating reasons related to time, etc.
- other members trying to listen to sections to be administered in privacy
- respondents unable to quantify consumption amounts in units
- long and damaging breaks if tablet needs to be restarted
- error messages flagging gross mismatch in harvest quantities, land size and sale prices

Record different ways in which a challenge may manifest itself or how the interviewer can recognize them in the field, using colloquial terms or used by respondents where it applies. As an example, respondents may say *"I am really busy "*, *"I need to leave"* or *"I need to cook/wash/..."* when refusing and stating reasons related to time.

For each challenge, identify good interviewer responses. These can include verbal responses actions or procedures. Often, there is no single response to a challenge that works equally well with all respondents and in all circumstances. Good interviewers often have a repertoire of responses and tailor them to observable features of the respondent or the context. For example, if a respondent refused based on time and appears to be rushed or pre-occupied about something (e.g. fighting children) the best response tends to be to ask for a different moment, e.g. by saying *"I see that now is difficult. When would be a good moment for me to come back?"*. However, if the respondent refuses because they have to do a chore but seems generally collaborative, it is often good to offer to do the interview while they do their activity. 

For each challenge, also record bad practices or responses that interviewers should avoid, if there are any. As an example, if respondents do not know the quantity consumed of an item, a bad probing practice would be say *"Was it maybe 1 kg?"*, as this is leading the respondent to answer 1 KG. 

Allocate challenges and responses into separate modules by topic, importance and anticipated time required to train. It is usually good to have at least one module on *Introduction and interview request*, one on *Inquiring and controlling interview* and one on *Challenges observed during field testing*. You might need additional modules on key questions or sections, such as *Estimating land size* or *Conducting consumption module*. 

Ideally, challenges and responses should be compiled prior to the training to facilitate planning and make training sessions more productive. Use a combination of any of the following sources to identify challenges and responses:

- experience from previous surveys with similar context, populations and subject
- focus groups with experienced interviewers
- observations and feedback from pre-test or pilots

If you are unable to prepare prior to the training, use challenges and responses observed during field practice sessions or hold short "focus groups" with the class at the beginning of each module. 

See HERE be a core set of challenges and responses that are common to many surveys. && NOTE: WOULD IT MAKE SENSE TO COMPILE ONE?

### Train & Practice

Schedule modules on interviewing techniques just prior to field practice and final field tests so trainees can apply the techniques soon after. Additionally, you might need to schedule some modules after field practice and field test to practice new situations that came up during field practice or retrain those that do not yet work well. Module between 45 min and 1.5 hrs tend to be sufficient to cover one core topic. 

For each module, first train interviewers on what challenges are likely to occur and what the best response are. Project the list of challenges, categories and good responses on the big screen. Work through each category, identifying together with the class the ways in which challenges may manifest themselves and any tips and tricks for a good response. Also cover bad practices that interviewers should avoid. Ask trainees that are good at a technique (experienced or good inter-personal skills) to demonstrate the best practices in front of class in a role play. Give feedback if necessary and ask the class for input to get consensus and make sure responses are appropriate for culture and context. Try to keep this part short.

After having covered the theory, drill trainees until they are able to respond to a challenge quickly, correctly and in a natural manner. This is best done by asking trainees to simulate the interviewer-respondent interaction in front of class in a role play, providing immediate feedback and letting them repeat if necessary. Depending on class size and skill level, it might be best to divide the class into large groups, each supervised by a trainer. 

To practice, select one trainee to act as interviewer and if needed another one to act as respondent. Usually, it is more useful for the trainer to act as respondent as it allows them to better drive the conversation. Ask the selected trainee to come to the front or just stand up and speak towards the class, which is often faster. Explain the scenario and challenge and ask the trainee to re-enact the interviewer response as if it was a real field situation, speaking loudly so the entire class can hear. Give feedback on what they have done well and what not. Ask the class for inputs. If the response could be improved, ask the trainee to repeat the response. Collect feedback, correct them and ask them to repeat until the trainee does it well. Practice with as many trainees as possible or until the response generally works well. This can be quite a lot of fun and is a good way of breaking longer theoretical sessions.  

Two examples to illustrate: 

To practice introduction to the survey, select one trainee, ask them to stand up, tell them that they just knocked at a door, a certain type of person opened, that they should introduce themselves and ask for participation. Check that they are giving all necessary information, say nothing wrong, are easy to understand, use the right tone of voice, have good facial expressions and gestures, etc. Collect feedback from the class. Ask the trainee to repeat their introduction until it is correct in content and well presented.

To practice asking for participation, ask a selected trainee to make an introduction and ask for participation as above. Act as respondent who is unwilling to participate, stating one of the challenges discussed in the training, such as such as _“I am really busy now”_ or _“What do I get out of this?”_. Ask the trainee to respond and convince you to participate. Again, together with the class, check if the trainee's response was quick, correct and natural. Give feedback on possible improvements and let the trainee repeat their response until satisfactory.   

## Special tasks 

For some surveys interviewers need to learn a special task that requires repeated and structured practice until they can perform it correctly and on auto pilot. This can take As a trainer, you need to identify trainees who are struggling with the task and be aware of scenarios that cause issues. Examples for special tasks are:  

- Plot size measurement 
- Anthropometry 
- Collecting samples, e.g. to measure water quality 
- Extracting information from registries, records, etc. 
- Behavioral games 

Typically, these tasks require interviewers to strictly implement a protocol, use additional tools or aids or understand differently structured documents. Explaining the theory and going through one example is not enough. You need to practice in a structured way and evaluate trainees, exposing them to different scenarios if necessary. The best way of doing this depends on the task at hand.  

One option is to run through scenarios together so all trainees practice the same thing at the same time. For example, if interviewers need to record details from school time tables, display a picture of an actual timetable from a school on the big screen, and ask trainees to record the required information on their tablets. Run through examples of different time table formats, so interviewers get used to different scenarios. Walk through the class and identify any trainees who are struggling. Provide feedback and discuss in the wider class if there is any confusion. If interviewers need to perform a task on automatic pilot, for example, operate testing equipment, ask the class to repeat it over and over until everyone can perform it correctly all the time.  

Another option is to set up workstations that interviewers need to go through. Set up different scenarios in or around the venue and staff some with trainers if necessary. Trainees go from station to station and complete the respective task. At the end, each trainee should have undergone the same scenarios and a general debrief can be held. Trainers can observe each trainee at their respective station, evaluate and provide personal feedback. Set up stations such that interviewers spend their time practicing, not queuing. Examples for workstations can be plots with different shapes and cultivation, trainers playing common scenarios in behavioral games, or different documents that need to be evaluated. 

### Specialized teams 

If a task is very complicated, requires special background knowledge or if there is not enough time to train it well to all interviewers during the training, field work model permitting, it is often best to specialize some fieldworkers to exclusively conduct the task and distribute them across the field teams. Examples where this tends to be useful are: 

- Anthropometrics, especially when taking all measures, i.e. weight, height/length and middle upper arm circumference (MUAC)   

- Learning outcome assessments used in school surveys that include reading, writing and math tests with strict administration protocols.   

- Medical tests, such as taking blood pressure or measuring hemoglobin values. This often requires the use of specialized equipment and trained nurses. 

Training any of those tasks can take several days. For example, learning outcome assessments require trainees to handle test booklets, CAPI and a timer all at once while keeping a young child engaged. It usually takes days to practice until all trainees can conduct the assessment tests in a homogenos way, and not everyone is good at it. 

Train selected trainees in separate sessions in parallel to the interviewer training. Practice all components of the task, including the equipment use, measurement reading, and interaction with the respondent. Invite practicing respondents to the training venue to practice the human component and create closer to field conditions. For more details, see section Inhouse respondents.  

For anthropometrics, the components that need to be practiced include the correct setup of scales and height/length boards, taking the measurements, how to treat the children/babies, reading the measurements (careful, some are dislexic), and recording them. At the beginning, the measurements taken for the same person differ quite a bit between trainees. Practice until they converge after a few days.


* parallel sessions


## Pre-interview tasks

better trained towards the end of training, prior to field practicing or final field tests, so interviewers can practice in the field immediately, no point in covering in detail at the beginning since most of it will not be used for a few days 


- identify & track respondents
- cover section in sursol, how to create interview file
- when and how to revisits
- replacement protocols 
- how to identify households
- selection protocols, if e.g. in field sampling using kish tables.

- prep maps, tracking sheets, discuss explain protocols 

- some parts might require exercising, e.g. how to use kish tables for in-field selection

?? TEAM: any comments on required content and modality?

## Post-interview tasks

??Team any other post-interview tasks?

In some surveys, interviewers receive feedback or inquiries about interviews they have submitted that require them to take some action or respond. In Survey Solutions, this is done using rejected interview files. This often goes wrong in surveys and needs to be covered in the training if implemented in the field. There is a big risk that interviewers “fix” interviews by simply changing answers to make issues go away, without actually addressing the underlying problem. Interviewers need to understand what they must and must not do. Train and practice in a dedicated session towards the end of the training. 

Ideally, trainees can practice with actual examples from interview files they have produced themselves. This makes it less theoretical and shows trainees that they made mistakes and what they were. You can use interview files from the field test (LINK) or even better, the final dress rehearsal (LINK), as interviews will generally be of better quality. This implies that the session needs to be held towards the very end of the survey.  

Prior to the session, carefully review submitted interviews and identify any issues. Normally,  at the beginning there tends to be at least one per interview, make up some if there are none. Write comments and feedback as would be written during field work and reject the interviews to the interviewer. Try to do this with at least one file per trainee/pair. 

During the session, first give a quick general introduction to explain the rejected files tab on the interviewer dashboard, how to open a rejected file, how to read the rejection comment, how to see all comments by the supervisor, how to react to rejected files, respond to comments and resubmit them by marking them as complete and synchronizing.  

Then, project a rejected interview to the main screen and ask the respective trainee/pair to come to the front. They should explain what led to their mistake and what they should do if this occurred in the field. Ask them to respond to the issues and resubmit the file on screen. Ask the class to help and comment. Repeat this with as many files/trainees as possible and useful. Ask all trainees who did not solve their file on the big screen to solve it on their tablet and resubmit them. 

This exercise is also a great way to identify and streamline the rules around responding to rejected files, revisiting respondents, etc. For more information see chapter REJECTING FILES.
 
## Final field test (often called pilot) 

At the end of the training, a final field test should be conducted in which all survey questionnaires and protocols are tested under real-field conditions prior to field work. It is an important exercise to:  

- Expose interviewers to field-like conditions and give them the opportunity to practice without affecting the sample 
- Determine if the field team is ready for field work 
- Identify and address any outstanding issues with questionnaire or field procedures  

Some surveys do not conduct a separate [pilot](#pilot) prior to the training and refer to the final field test as pilot. In those cases, the final field test importantly also serves as a reality check for questionnaires and protocols, since they have not been tested in full under field conditions before. 

The dfinal field test should be conducted at the end of the training and prior to the field work. Usually, 2-3 days of final field testing are necessary but also sufficient. If short debriefing/feedback sessions can be held in the late afternoon of each day, they can be on sequential days. If not, schedule debriefing/feedback days between field days. Allow for at least one class room day after the final field test for an extensive feedback session and to teach the class on how to deal with rejected files, inquiries from HQ or any other post-interview tasks. Additionally, you might need to allow for additional time for admin, rest days or travel to the field location.  

To create as close conditions to the field as possible, the final field test must be conducted with units that are similar to those in the survey sample, but crucially that are not part of the sample. For household surveys, this usually means conducting the final field test in un-selected communities within the survey areas and often requires the team to travel from the training location closer to the field. For surveys part of RCTs, this means practicing within the treatment areas. 

Ideally, locate the dfinal field test such that the entire field team can be supervised and debriefed together in a central location. This ensures that all field workers have received the same inputs and reduces team effect. Split the final field test into different locations if there is a large variability in the sample that affects questionnaires or protocols. If doing so, try to streamline as much as possible the supervision and feedback given to all groups, e.g. by trainers exchanging notes before providing feedback to their respective group. 

Often it is easiest to select a set of testing PSUs (e.g. communities) during the sample design and have them undergo the same preparation steps as the sampled units, e.g. assignment of IDs, procurement of reference data, add them to the CAPI questionnaire, do community sensitization, etc. For surveys with a separate listing exercise or panel surveys, conduct the dress rehearsal for all stages using the same units and keep the data, so you can properly prepare and test each stage of the survey. It can be very laborious and cumbersome to prepare separate data.   

One important aspect of th efinal field test is for field workers to practice the selection, identification and tracking of survey units such as households, convincing respondents to participate and to learn how to make appointments and to manage time. Do not pre-arrange respondents as one would do during field practice. Equip interviewers with the same assignments or tracking sheet format they would receive during field work. If you do not have lists or names for the rehearsal units (e.g. you have the household names for sampled communities, but not for practicing communities), send someone to the community prior to compile lists that you can use to produce the assignments/tracking lists.

Allocate interviewers to their expected field teams and let the supervisors assume their management role, including the assignment of cases to interviewers. For the final field test, often it is beneficial for interviewers to conduct interviews in pairs. This reduces the number of cases required in any of the visited communities, increases the probability of finding available respondents and allows interviewers to help one another. Each pair can conduct multiple interviews per day and take turns in administering the questionnaire. As in the field tests, both interviewers should record all answers in their own tablet and submit the interview in the end.  

For the final field test you might need to relax replacement protocols and add additional replacement units, so interviewers can practice conducting some interviews even if non–response is high. 

Make sure field teams arrive early in the communities, so that interviewers have enough time to locate cases and conduct interviews before respondents start cooking/having lunch and become unavailable. As for the field practice, make all necessary logistical arrangements to prevent delays or hungry/thirsty field workers in the field.  

Collect feedback and debrief as described for [field practice](#field-practice). Ask all interviewers to submit their interviews at the end of the day. Use the data to finalize your data system and quality control system, e.g. by updating the data checks. Review submitted interviews using the standard processes of the quality control system. In addition, visually review as many cases as possible and compile feedback for interviewers and the quality assurance team.  

The data collected during dress rehearsal is a great way to learn and practice receiving feedback with the team, see chapter feedback.

## Supervisor Training

??Team: any inputs?
DHS has some (limited) material 


## Data Monitor Training
??Team: any inputs?

