# (PART) Training {-}

# Introduction


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, comment = FALSE, message = FALSE)
```

Longer Training reduces interviewer effect (quotation needed, see e.g. Fowler, Floyd J., and Thomas W. Mangione. 1985.)

Few survey components affect data quality more than fieldwork training. Yet, unfortunately in many surveys, fieldworker training is neglected, under budgeted or implemented so poorly that there is little learning happening. No field work monitoring tool or exercise can fix a training that has failed to produce fieldworkers who are fully capable of accurately implementing the survey.   
This chapter describes how a successful interviewer training can be conducted. If you only have a few minutes, read the key points in subsection 1(LINK). If you are looking for more detail, read the relevant subchapters before you get to this point in the training preparation or delivery. 

If you are after a quick "cheatsheet" version, read our [key recommendations][Key Recommendations] on training in Chapter \@ref{training-tldr}.

Chapters X to Z are written with an in-person interviewer training in mind. 

Chapter \@ref(planning-and-preparing) [Planning and Preparing] provides you with the details you need to plan and prepare a good interviewer training, including what content it should cover, when it should be held for how long, how many trainers and trainees should be involved and some check lists for logistics. Read this prior to budgeting and planning your training. 

Chapter Y gives details on how to conduct an effective interviewer training. It gives some general considerations and hands-on gives tips and tricks for the different session types such as questionnaire reading, on-side or in field practicing. It is targeted towards trainers and is best read prior to the training or before conducting a particular session type.

As you will learn in this chapter, you should train an excess of interviewers, assess them on an ongoing basis and select them at the end of the training. Chapter \@ref{trainingassessment} [assessment](training-assessment) gives important considerations for this process and step-by-step guide on how to do this.

Chapter ZZ gives considerations for special training arrangements, including remote training, training of trainers or online training. 



## Key Recommendations

This tl;dr is for readers who want to see our “cheatsheet” version of the chapters on training. If you are looking for more details, we think you’ll benefit from reading the rest of the chapters. Follow below key points to ensure a successful interviewer training. 

1. __Train an excess of 20-40% of field workers__ and select them based on skills at the end of the training, even if working with experienced teams. Trainees take the training more seriously, pay attention, and learn and the overall skill level of field workers is higher.  

1. __Continuously evaluate__ trainee performance and capacity in written tests, role plays, questions in class and observing them while practicing. 

1. __Don’t cut on duration__! Allow for at least one full week of training per 1.5 hours questionnaire length. Anything less is normally not enough for the complex content of a socio-economic questionnaire to be learned and practiced.  

1. __Keep it small__. Try not to train more than 50 persons at a time, so you get to know the strengths and weaknesses of the trainees. Adjust field work to take longer to allow a smaller field work team.  

1. __Make it interactive__. Avoid one-directional presentations that overwhelm trainees with too much information. Involve trainees and frequently change the training modality.  

1. __Practice__. Frequent practicing is crucial for trainees to fully internalize the content and be able to apply in the field. Practice on-site and in the field.   

1. __Be prepared__. Make sure questionnaires, manuals and tests are truly ready prior to the start of the training. Have the venue fully set up and all admin and logistics sorted.  

1. __Focus__. Only teach what interviewers need to know to do their work well. Spend more time on things that are crucial to the survey. Instead of giving a 2hr presentation on the analysis of the data, give a short introduction and practice with interviewers how to introduce the study in the field.  

1. __Enough trainers__. Delivering good training is more than a full time job. Many things need to happen in parallel to the training being delivered. More trainers are usually better, and best if stakeholders, designers and analysts are among them. 

1. __Engage__. As a survey designer, do not do your emails on the side table and leave it to the survey firm, fieldwork manager or trainers alone to deliver the training. Actively participate, check that the content is correctly understood, explain what matters, etc. You have put a lot of effort into the design. Make sure it is implemented correctly.

1. __Trainers need expertise__. Sending a junior colleague without much experience to be in charge of the training is not a good idea. You need solid survey, context and subject experience among the trainers to deliver a solid training.    
