# (PART) Fieldwork Training {-}

# Introduction to Training {-}

Fieldwork training is arguably one of the most important activities of any survey and has one of the biggest impacts on data quality. It serves several purposes: 

1. __Build fieldworker capability__. In-depth content training, extensive practicing and capability-based selection ensure that fieldworkers are capable of implementing the survey as designed. This is key to limit [measurement](#measurement-error) and [nonresponse error], as well as [coverage](#coverage-error) and [sampling error] if the survey includes listing and in-field sampling.  

1. __Standardize fieldworker behavior__. Repeated practicing under supervision and continuous feedback streamlines how fieldworkers implement the survey. Reducing idiosyncratic behavior is important to mitigate the very damaging [fieldworker effects](#impacterror).

1. __Scrutinize methodology__. Particularly in surveys with limited pre-testing and piloting, fieldwork training often effectively is the most detailed review of the questionnaires, translations, CAPI and survey processes. Identifying and correcting mistakes is key to reduce [specification error].

<!-- Longer Training reduces interviewer effect (quotation needed, see e.g. Fowler, Floyd J., and Thomas W. Mangione. 1985.), 

training survey request reduces non-response, see Groves 2001 -->

Unfortunately, in many surveys fieldwork training is not effective in producing fieldworkers that are fully capable of implementing the survey, or is inefficient in being too demanding on trainers and survey budget and timeline.

This part of the book gives recommendations on how to implement fieldwork training that effectively prepares field workers while not while not overburdening trainers or overstretching survey resources. It assumes fieldwork training to be in-person, as is custom for most socio-economic surveys with personal interviews. For remote training, check XYZ ??QUESTION Do we have any resources?   

Readers who are interested in a cheatsheet version can read the key recommendations for fieldwork training in the TL;DR below. Those looking for more detail will benefit from reading the respective chapters. 

Chapter \@ref(planning-and-preparation) [Planning and Preparation] is targeted at survey designers, managers, fieldwork managers, trainers or any other role that is involved in the planning, budgeting and preparation of the fieldwork training. It provides recommendations on the training location, timing, size, the trainers, training content and schedules, and includes checklists of the key items to prepare prior to the training. 

Chapter \@ref(conducting-the-training) [Conducting the Training](#conducting-the-training) gives useful recommendations on how an effective and efficient fieldwork training can be conducted. It provides extensive details and step-by-step guides for different training modules. It is mainly targeted towards trainers and is best during training preparation and the training itself.

LSMS strongly recommends a capability-based selection of fieldworkers at the end of the training, informed by a continuous evaluation of trainees throughout the training. Chapter \@ref(assess-select) [Assess & select fieldworkers](#assess-select) is mainly targeted towards trainers and gives step-by-step guide on how to effectively implement written tests, systematically evaluate skills and select fieldworkers. Survey desigeners and managers may be interested in reading about the benefits of this approach that are summarized at the beginning of the chapter.  
  
  
:::tldr
<h2>TL;DR<span style="color:#17BEBB;">.</span></h2>
Follow below key recommendation to ensure a successful fieldworker training. 

1. __Train an excess of at least 20% of fieldworkers__ to allow for meaningful competency-based fieldworker selection at the end to have a fieldworker reserve. If working with unknown teams, mainly new recruits, or expect high attrition, increase the excess to 40% to ensure capable fieldworkers. 

1. __Select based on skills__. Continuously evaluate trainee performance and capability in written tests, role plays, questions in class and observing them while practicing. Select fieldworkers at the end of training in a transparent process based on their capability and skills. 

Select roles based on skills__ who wil be supervisor, data monitors, etc 


1. __Train an excess of 20-40% of field workers__ and select them based on skills at the end of the training, even if working with experienced teams. Trainees take the training more seriously, pay attention, and learn and the overall skill level of field workers is higher.  

1. 

1. __Don’t cut on duration__! Allow for at least one full week of training per 1.5 hours questionnaire length. Anything less is normally not enough for the complex content of a socio-economic questionnaire to be learned and practiced.  

1. __Keep it small__. Try not to train more than 50 persons at a time, so you get to know the strengths and weaknesses of the trainees. Adjust field work to take longer to allow a smaller field work team.  

1. __Make it interactive__. Avoid one-directional presentations that overwhelm trainees with too much information. Involve trainees and frequently change the training modality.  

1. __Practice__. Frequent practicing is crucial for trainees to fully internalize the content and be able to apply in the field. Practice on-site and in the field.   

1. __Be prepared__. Make sure questionnaires, manuals and tests are truly ready prior to the start of the training. Have the venue fully set up and all admin and logistics sorted.  

1. __Focus__. Only teach what interviewers need to know to do their work well. Spend more time on things that are crucial to the survey. Instead of giving a 2hr presentation on the analysis of the data, give a short introduction and practice with interviewers how to introduce the study in the field.  

1. __Enough trainers__. Delivering good training is more than a full time job. Many things need to happen in parallel to the training being delivered. More trainers are usually better, and best if stakeholders, designers and analysts are among them. 

1. __Engage__. As a survey designer, do not do your emails on the side table and leave it to the survey firm, fieldwork manager or trainers alone to deliver the training. Actively participate, check that the content is correctly understood, explain what matters, etc. You have put a lot of effort into the design. Make sure it is implemented correctly.

1. __Trainers need expertise__. Sending a junior colleague without much experience to be in charge of the training is not a good idea. You need solid survey, context and subject experience among the trainers to deliver a solid training.    

1. __Assess readiness for field__. At the end of the training, a final field test that mimics field conditions. where field workers can be observed and feedback given without using the actual sample. If team is not ready, e.g. there are common outstanding issues, extend the training by a few days to revisit and strengthen problematic areas. 

1. __Interviewing skills__ are essential. Not all trainees possess them. Especially new recruits need to learn and practice how to introduce the survey, respondents to participate, maintain the repsondent responsive, elicit responses for difficult questions.  

1. __Only select capable interviewers__. Only select interviewers that have demonstrated full understanding and capability of satisfactory and reliable completion of required tasks. If there are more than needed and you have flexibility, you can  have slightly more teams operate over shorter time as long as overall size is kept at bay.  If not enough trainees are available, extend training.    

1. __Specialize fieldworkers__. For surveys with many questionnaires or special tasks such as anthropometric measurements often it is too much material for trainees to learn how to do well in a short amount of time. See if you can divide tasks between different fieldworker roles and train them in parallel. 

::: 
