
# Conducting the training

This chapter targets trainers, providing details on how to deliver effective and efficient interviewer training that facilitates learning without overstretching survey resources. The chapter assumes in-person training as is the case for most surveys conducted with in-person interviews. The first sub-chapter covers general considerations for the training. The remainder of the chapters is organized by training module. Each sub-chapter provides details on the rational, optimal timing and recommendations for the implementation of the respective module. See the [training schedule](#trainingschedule) in Chapter \@ref(planning-and-preparation) on how individual modules relate and are best combined.   

Prior to the start of fieldwork training, make sure everything is [fully set up](#trainingpreparation).

## General considerations

Throughout the fieldwork training, consider the following points:  

- __Essentials only__. Only train fieldworkers on things that are relevant for them and that their respective role is required to do. For example, there is no need for interviewers to learn details about the survey analysis or the supervisor role/functionality in the CAPI software.   

- __Confirm with designers/analysts__. If trainers are uncertain in the interpretation of concepts, questions, or responses, it is important that they keep notes to run these by designers/analysts on a daily basis. Ask them to be on standby so you receive timely responses. Provide updates and clarifications to the trainees in a timely manner. 

- __Eliminate language barriers__. Do not train in a language the trainees are not fluent in. If some trainers (usually the survey designers or analysts) do not speak the training language, use an interpreter or ask other trainers (e.g., fieldwork manager) to translate or reiterate their points in the training language.  

- __Support trainees__. Especially during the first few days, trainees often get lost in the CAPI application or questionnaire flow and are unable to follow the sessions. Trainers who are not actively leading a session should walk around the class, check that trainees are in the right place and support those falling behind.

- __Probe for understanding__. It is wrong to assume things have been understood just because no one speaks up when you ask *“Any questions?”* Ask questions on specific questionnaire details using common examples or scenarios. Ask variations of your test questions. For example, think of working profiles/jobs that are typical in the surveyed population and probe trainees if these are wage employed or self-employed.   

- __Encourage questions__. From the beginning, make it clear to trainees that they should ask if they have ANY question, that it is better to ask than to remain with a doubt, and that there are no bad questions. Take questions seriously and address them. If trainees prefer not to ask in front of the class, they can raise their hand and be visited by a trainer. 

- __Involve trainees__. Ask frequent questions. Let trainees read aloud questions and manuals. Ask them to correct one another. Avoid always picking the most engaged trainees and try to involve everyone. Select a trainee using a [random name picker](https://wheelofnames.com){target="_blank"}, so it can be anybody’s turn to answer your questions at any moment (they make it fun if displayed in front of class). Another idea is to select the person closest to where a paper ball lands that you or anyone throws over their back. To speed things along, let each trainee you call on cover a couple of survey questions. 

- __Get to know trainees__. Ask trainees to wear name tags during the first few days. Learn their names as quickly ass possible. This makes the training more personal and helps trainers to better connect trainees' in-class performance with written tests or test interviews. 

- __Collect and react to feedback__. At the end of each day, use feedback forms to collect anonymous feedback from trainees on how clear different sessions or trainers were, topics they did not understand or questions they have. Review feedback forms prior to the next day and adjust your training schedule or methods if needed. ??KEVIN: provide feedback form example.   

- __Break up and mix groups__. If you start noticing groups of trainees sitting together who are not paying attention or are at the bottom end of performance, distribute them across the classroom. Ask low performers to sit next to high performers, so they can help when falling behind. Avoid always grouping the same people for exercises, to ensure that everyone has the same understanding of the material. 

- __Make it fun__! Maintain a general positive and fun attitude. Play fun and exciting [group games](https://www.sessionlab.com/blog/large-group-games-and-activities/#){target="_blank"}. The last person entering the venue late and unexcused can sing a song in front of the class (YouTube is full of Karaoke videos). Hold an end of training party. 

- __Use video & audio__. It can be a good way of demonstrating certain things like interviewing techniques or special tasks to trainees, so they can see/hear what they should and should not do and learn from examples. Use existing material if it is good, or collect video/audio material during pre-test, pilots and field practices to demonstrate good and bad practices to the class. 

- __Stress importance__. Make it repeatedly clear to the trainees that it is important that they do a good job, that the survey result and ultimately policy and decisions depend on it. Give them a sense of purpose. Like any other human being, interviewers perform better at work if they care about what they do.

- __Trainees are responsible for their learning__.  Make clear to trainees that it is up to them to ensure they have understood the covered material. They can read the manual, practice outside the class, learn from peers, ask questions, etc. to make sure they understand everything. Let them know there is a transparent and objective selection process at the end and they must pass it to become a fieldworker.

- __Set and enforce rules__. Trainees must attend and sign attendance every day. Ask trainees to be on time and respect training hours yourself by not running late or running over time. No side conversations, no (excessive) use of cell phones and no phone conversations in the training room. Enforce rules in a fun but serious way, e.g., anyone breaking rules can donate to a cookie jar, has to hand in their cell phone, sing a song, etc.  

- __Zero tolerance for cheating__. Make it clear from the beginning that there will be serious consequences for anybody being caught intentionally making up data or purposefully breaking protocols (ideally being immediately dismissed). Also make clear that fieldworkers have nothing to fear as long as they follow what has been taught during training and check with supervisors or fieldwork managers if they are unsure about anything. 

- __Daily trainer meeting__. Trainers should meet daily at the end of the day to compare notes, evaluate progress and trainee performance, review tests and class feedback and adjust as needed the plan for the following day(s). If field supervisors are pre-determined, include them in the meetings.

- __Document__. Throughout the training, note down any changes to the methodology, known problems and general training details, so the details are available for data documentation and to inform future training or survey rounds. 


## Welcome/introduction

The welcome/introduction session serves to introduce trainees to the survey and training. In many surveys, this is  unnecessarily long and involves too many people. Keep it as short as possible (1-2 hours are enough) so that some content can still be covered on the morning of the first day. In the welcome/introduction session cover:

- __Opening speeches__. Try to keep speeches by officials or leaders as short as politically possible. Also, if possible, avoid making the opening/start of the training dependent on the arrival of guest speakers and government officials, as they might be late (e.g., start with introductions in the meantime).

- __Introduction to survey/organization__. Give a brief introduction of the survey, its objectives, the organizations involved, the project/study, etc. Do not go into too much detail here, limiting it to what is essential for fieldworkers to know. If needed, provide more details in the manual and refer trainees to it. 

- __Introduction of trainers and trainees__. All trainers and core survey team should briefly introduce themselves and their roles. If the class size is large, avoid introduction rounds for trainees as they tend to be dull and ineffective. Play a fun ice breaker instead. ask all trainees and trainers to write their name on a name tag and wear it during the training.

- __Training plan__. Give an overview of the rough training schedule and daily working hours. Explain the need for punctuality, that there will be frequent tests and evaluation of skills, that trainees are responsible for their learning, that all questions are encouraged, and that there is zero tolerance for cheating. Point out that the rules and procedures for this survey may be different than in other surveys they might have worked on and that trainees are expected to learn and follow the procedures and rules covered in THIS training (and not those of other surveys).

- __Survey details and terms__. Run through the overall survey parameters and contract terms, including the selection process, their remuneration package, insurance coverage, areas to be visited, the expected length of field work, the transport and lodging arrangements during field work, expected effort, etc. Importantly, this should be a refresher and NOT the first time trainees learn details about their pay, other terms or the fieldwork. Make sure all trainees have understood and signed a copy of the general terms prior to the training.

- __Administrative/contractual matters__. If you need to address administrative or contractual matters with trainees – contract signing, registering for insurance, signing out tablets, etc. – try to do this as much as possible before regular training sessions (e.g., from 8-10 AM), or in another dedicated slot. Trainers do not need to be present.   

## CAPI use

This chapter is based on using Survey Solutions, but the same principles apply to other CAPI software packages.

CAPI, like any other software, __is best learned by using it__. Covering all functionality in a long theoretical session tends to be very ineffective as any functionality that is not immediately put into practice by trainees is forgotten and needs to be retrained later when it is used. It is more productive – and a better use of time – to start by covering only the basic functionality necessary to begin training, and to gradually introduce additional functionality as required throughout the training. For example, trainees do not need to learn procedures for rejected interviews until they learn about post-interview activities in the latter part of training.  

Limit the functionality you train to what is relevant for an interviewer and what will be used in the actual survey. For example, trainees do not need to learn how the Supervisor interface works, what exactly happens at HQ, how assignments are processed or what a multi-select question type is if there are none in the questionnaire.

The fewer slides you have in the CAPI training, and the more demo and practice you do, the better it will be. Train functionality by demonstrating it on the big screen and asking trainees to follow on their own devices. Make sure the class can follow and wait for anyone falling behind to catch up. If someone is lost, they should check with their neighbors or raise their hand, so one of the trainers can come to assist. For example, show on the big screen how to log in to the Interviewer App. Wait until all trainees are logged in on their tablets. Then, show on the big screen where to find an assignment card, explain what it is and show how to create a file. Wait for everyone to open an interview file on their tablet, and so on. Clarify any questions or doubts trainees might have along the way. 

You can __train the questionnaire directly in CAPI__, without training it on paper first, if you are using Survey Solutions or another CAPI software that provides a good overview of the questionnaire, makes routing behavior clearly understandable and allows for free navigation between different parts of the questionnaire. This is usually not the case for software that shows only one question per screen.

Training the questionnaire directly in CAPI has the advantages of requiring trainees to only learn the questionnaire in the format they will ultimately use in the field (e.g., no need to learn how skips work on paper). This also means CAPI will be introduced earlier in training and be used more frequently throughout, allowing trainees to more quickly become confident in using the CAPI questionnaire and the CAPI software in general. New trainees do not notice any difference, and experienced trainees who are used to paper questionnaires usually stop missing them after a day or two. 

Train the basic CAPI functionality just before trainees use it for the first time. Usually, around 1 hour is enough. If you are training the questionnaire on paper, train the CAPI basics just before trainees practice for the first time on the tablets, usually on the first or second day.

If you are training the questionnaire directly on CAPI, introduce the CAPI basics just before starting with the questionnaire content, usually on the morning of the first day. 
For Survey Solutions, cover the following topics in the initial CAPI session: 

- A general overview, including how the Interviewer App and HQ server interact, what assignments and interview files are, and what synchronizing does. Keep this part short.

- How to log in to the Interviewer App. and how to create an interview file from their assignment. (Trainers should confirm with design and IT teams that tablets and user accounts have been set up prior to the beginning of training).  

- A general overview of the Interviewer App, questionnaire layout, and how to navigate through the questionnaire.  

- The outline of a question, the question number, the question text (what to read and what not), the instructions, the answer options (different by type). 

- Question and section enablement for the first questionnaire section. Other examples can be presented and explained when training covers those sections.  

- The complete screen, marking an interview as complete. 

- The dashboard screen/view for Started and Completed interviews, including reopening an interview file and discarding an interview file. 

Having completed the above steps, trainees should be able to follow in the questionnaire during the questionnaire content modules. The remaining CAPI functionalities are best trained throughout the training when they are used for the first time:

- During the questionnaire content modules, train the different question types, roster forms, static texts, sections and sub-sections as they come up. For example, explain fill-in lists during the household member module, yes/no filter questions in assets, etc. Trainees need to recognize and understand the difference between single select, multi-select, numeric, list and date questions, and understand how rosters function. 

- If using Survey Solutions, prior to practicing or the first [written tests](#written-tests) (if done in Survey Solutions), train how to synchronize devices to receive assignments; how to create new interview files and review interviews on the complete screen; marking interviews as complete and synchronizing to send a file. Conducting the tests on CAPI tends to be useful, as trainees need to correctly synchronize to get the questionnaire/assignment and submit their test (send the completed interview file).

- Prior to group or field practice, train how to insert comments at questions and at synchronization, so that trainees can leave concerns or comments directly in the interview files when practicing.  

- After field practice or the final field test, train how to receive rejected interviews, respond to comments, and resubmit rejected interviews. This will allow trainees to practice [post-interview activities](#post-interview-activities) using interview files they have created themselves.  

## Questionnaire content


:::: {.warning data-latex=""}
A single, joint reading of a questionnaire is not sufficient for trainees to learn and understand the various concepts, definitions, and scenarios that are necessary to correctly administer a socio-economic questionnaire. Some implementing agencies (e.g., survey firms accustomed to implementing opinion surveys) might not recognize the effort required for complex socio-economic questionnaires and will vastly under allocate training time for questionnaire content.
::::

Trainees must understand the entire questionnaire(s) in detail, including underlying definitions and concepts. Usually, this makes for a substantial amount of material to be covered which, if not trained well, can be quite dull and lead to ineffective use of time. Consider the following points to make the questionnaire content modules interesting and effective: 

- __Avoid long content sessions__. Covering the content of an entire questionnaire usually takes many training days. Avoid training content for more than 2 hours at a time. Long content sessions tend to be information overload for trainees, making it impossible for them to internalize the content. Instead, spread the content training over multiple days and let trainees [practice](#practicing) the newly trained material at least twice per day, e.g., after every long questionnaire section (or a few short ones).     

- __Less instructional, more interactive__. Avoid one-directional training methods in which trainers give long presentations or read through questionnaires without really interacting with trainees. This tends to be a very ineffective way of teaching questionnaire content. Instead, involve the trainees as much as possible. For each question (or a few at a time), select one trainee to read aloud the question(s) and any instructions, answer options or corresponding manual entry. Ask the trainee to explain in their own words what they have understood and how the question is to be administered. Make sure the rest of the class can hear them. Correct them if needed. Ask the rest of the class for input. Ask the rest of the class for input. Check if the trainee has understood by probing with an example. Give feedback on tone of voice and way of asking the question. Ask the trainee to read out the question again if needed. 

- __Explain the big picture__. At the beginning of each section (or part of the questionnaire if you have small sections), provide a brief general overview to the class, including overall structure and routing behavior, things to be aware of, key concepts and definitions, target respondent(s), etc. It is better to explain these details section by section (rather than once at the beginning of the training for the entire questionnaire), so trainees can immediately see and soon after practice what has been trained, and can thus remember it more easily. 

- __Go into detail__. Many questions have to be covered in more depth for interviewers to be able to administer them correctly. This can include explanations on the underlying concepts and definitions, how to categorize responses into the given answer options, common scenarios that require further probing, what error messages mean, what conditions open the question, how the question relates to other questions, how to sense check responses, etc.

- __Make it tangible__. Definitions for survey concepts such as *household*, *parcel*, etc. can be very theoretical and hard for trainees to translate into the real world. When training anything theoretical or abstract, always try to illustrate it with examples and scenarios that are common in the surveyed population so that it is easier for trainees to understand. For example, to explain what *wage-employed* and *self-employed* are, list jobs or work profiles that are common and show which category they fall into.

- __Use the manual__. The [interviewer manual](#manual) should hold all conventions on how to correctly administer the questionnaire.  To be correct, it must always be up to date. Also, trainees must develop the habit of consulting the manual for additional information or to clarify doubts, or it will never be used. Ask trainees to keep the manual open on paper or as a soft copy on their device. After reading each question, ask trainees to check if there is a corresponding manual entry and to read it as well. One of the trainers should update the manual directly during the training if the entry is unclear or insufficient. Ask for input from the class if needed and confirm with them if the updated entry is clear. Distribute updated soft copies of the manual to the team every morning/evening.

- __Use your time effectively__. There will always be a few rare cases in the population that the questionnaire does not cover well. Trainees love pointing those out, e.g., _“But what if ….?”_ If these scenarios are common occurrences, they are worth reviewing during training and may merit updating the questionnaire or manual. Training should cover the many scenarios that interviewers are likely to encounter, but this does not mean addressing every single hypothetical outcome or scenario that could possibly occur. For rare scenarios, tell trainees to leave comments in the questionnaire and discuss with their supervisors if the situation arises in the field and move on with the training. Spending a disproportionate amount of time discussing these infrequent cases is counter-productive and takes time away from more frequent and important scenarios.  

- __Multi-language questionnaires__. If the questionnaire has been translated into other languages, display the questionnaire in the training language on the big screen and ask each trainee to follow the questionnaire on their tablet in the local language they are most likely to use. For each question, ask it to be read in the training and local languages. This serves to verify the translation and to familiarize trainees with the questionnaire in the local language. 

- __CAPI__. If training the questionnaires directly in CAPI (recommended), show and explain any new relevant CAPI functionality as you work your way through the questionnaire. On the big screen, demonstrate how the questionnaire should be filled in, how different question types function (e.g., text questions with patterns, search in combo box, etc.), highlight instructions or other parts that are not meant to be read out, what responses trigger what enablement or validation conditions, the overall organization of a section and how to navigate it, etc. Ask trainees to follow on their tablets.    

- __Demonstrate__. Show how questions or (parts of) sections should be administered by role-playing that part of the interview in front of class. Trainers can participate and/or ask experienced trainees to act as respondent and interviewer. This is particularly useful for complex modules or parts that require inquiring, e.g., probing for the age of household members, a child nutrition module, sketching a parcel map, etc. Trainees can follow and record the responses on their tablet. Give immediate feedback, highlight any mistakes and parts done well, and provide additional information if necessary.     

- __Update the questionnaire & CAPI__. Depending on the level of pre-testing, piloting and subsequent change, the questionnaire, CAPI and translations may still contain issues that are uncovered during the questionnaire content training. Ideally, trainers not actively leading the training can make immediate corrections, as it tends to be less time consuming and allows corrected versions to be used sooner during the training. Be consistent and follow updating protocols when making changes, e.g., update the live version of the paper questionnaire, the CAPI and the translation sheet. Do NOT simply update the questionnaire on CAPI or local language only, as this will lead to inconsistencies, mistakes and survey error. Ask the class for input if useful, e.g., how to phrase a question, or what answer categories exist. If there are many corrections, ask a dedicated person in order to not slow down the training.  

- __Use samples__. If interviewers need to extract information from documents, certificates or packages, or have to evaluate or rate items, it is important to expose them to a range of different scenarios and standardize their assessments. Bring a set of diverse samples to the training and practice in a structured way. One option is to run through scenarios together, e.g., by projecting examples of school timetables on the big screen and asking trainees to record the required information on their tablets, or showing photos of different water access points and having trainees indicate the appropriate response code for each . Another option is to set up work stations with different scenarios and ask trainees to rotate through the stations, complete the required task and record the information on their tablets. Trainers can staff individual stations and provide personal feedback to each trainee.  

## Interview practice

Trainees should frequently practice learned material. Daily group practice and front-of-class interviews towards the beginning of training are effective ways for trainees to learn and solidify newly-covered parts of the questionnaires and to break up the monotony of questionnaire content training. In the latter half of training, practice interviews with respondents on-site or in the field to prepare trainees for fieldwork by exposing them to real-world scenarios and respondents. Each practice modality (described below) serves a different purpose. It is not recommended to use them interchangeably, but to combine them throughout the course of the training.

### Group practice 

Towards the beginning of the training, while new questionnaire content is being learned, frequent practice is important for trainees to familiarize themselves with the questionnaire, learn how to administer the questions and practice the use of CAPI. Good ways of practicing during this phase are *group practice* or *front-of-class interviews*. 

Hold __practice sessions every day__ that new theoretical content has been introduced, so trainees can put it to practice and internalize it better. Do not wait to practice until the questionnaire has been covered fully or until the end of the day if a lot of material has been covered. Instead hold 2-4 practice sessions per day at natural breaks (e.g., between sections) to practice the material/sections covered just prior. The change of training modality helps to maintain attention levels. Immediately repeating material helps trainees to understand and internalize it and helps to uncover remaining doubts. Practicing more frequently becomes unfeasible as each practice requires time to set–up.   

Group exercise can be effective for small groups of 2-8 trainees. Change group composition between exercises. When allocating trainees to groups, mix trainees and break up clusters that formed in the class, so that low/high performers and those paying more/less attention are distributed. Try to be efficient and not to waste time when creating groups. For pairs, ask trainees to practice with their peers in the row in front/behind. For groups, work out the number of groups *n* needed, and repeatedly count loud from 1 to *n*, pointing at a trainee for each number. Each number corresponds to a group, and each number/group can meet in a different point of the training venue, e.g., *“All number 4s, meet at the blackboard. All number 3, at the door...”*. 

Ask groups to practice the questionnaire sections that have been covered since the last practicing session. If there is time, groups can also practice all sections learned to date. They should not work through parts of the questionnaire that have not been covered yet.    

Give scenarios for trainees to ensure they practice scenarios that are likely to occur in the local context and cover all parts of the questionnaire. For example, when practicing the labor section, ask them to complete it for an employed individual, self-employed, supporting family worker, etc. 

??NOTE, add example scenario box?

Within each group, one trainee should read and ask the questions while another one answers them. After a few questions/sections the roles should be rotated, so each trainee had the opportunity to act as an interviewer or respondent. All trainees in a group should follow on their own tablet and record the answers, which at the end should be identical for all trainees within a group in theory. Ask groups to submit their interviews after the feedback session to motivate them to get it correct. 

Feedback after practicing sessions tends to be thin. Asking the class if there were any doubts, questions or comments often results in general silence. In order to receive better feedback, ask groups to actively come up with feedback points, note them on a sheet of paper including the trainees’ names, and to submit those to the trainers at the end of the exercise. Feedback points can be any question or doubt they have about questionnaire, definitions, scenarios, etc. or any mistakes they have found. You can set a minimum number of feedback points, e.g., 3 during the beginning of the training when things are not clear yet, and 1 towards the end of the training.  

Trainers should observe groups that have been allocated to them, correct mistakes and help struggling trainees on the spot, but also take note of the issues they observed for the feedback session. They should consider any issues, including the way questions were read or answered, the intonation, misunderstandings, questionnaire navigation, CAPI use, etc. While observing, trainers should also rate and record trainees' [skill levels](#rate-skills) and give individual feedback where necessary. 

Debrief with the entire class immediately after the exercise. Ask groups for their written feedback and discuss and answer their questions in class involving input from other teams/trainees. Ask trainers to provide feedback from their observations, explaining what was done wrong and also how to do it correctly. Ask trainees who have been observed to do something well to demonstrate to the class (e.g., how to explain a concept/question), so that all can learn from good examples.

### Front-of-class interview

Asking trainees to conduct (parts of) an interview in front of the class is a good way to demonstrate how interviews should (not) be conducted and evaluate trainee skills. It also shows if the class is able to spot any mistakes made and allows trainers to provide feedback on interviewing to the entire class. It is a good means of practicing after a good part of the questionnaire has been covered, and before practicing with respondents on-site. This exercise tends to take much longer than a normal interview, so either practice only parts of the questionnaire, or schedule several hours.

Project one tablet to the big screen on which the responses for the interview will be recorded. It is best to not change the tablet during the exercise.  

For front-of-class interviews, select one trainee to come to the front and act as interviewer in a mini-role play. Select one at random that has not yet been to the front. It usually makes sense to rotate trainees after a few questions (e.g., 5-10), so more trainees get the opportunity to practice in the front and make the exercise less monotonous. Ask the next trainee to prepare in the meantime and wait in front in order, so the rotation of trainees does not take up too much time.

Select someone to act as respondent throughout the whole exercise. This can be another trainee, or preferably one of the trainers or a real respondent. Using a trainer has the benefit that they can direct the interview with their answer and probe if some scenarios are understood. Using real respondents exposes the trainees to scenarios and respondents that are closer to what they expect to find in the field. For real respondents, hire a person that is similar to the surveyed population to visit the training venue for the afternoon/morning.

Ask the interviewing trainee to administer the questions as if they were in a real interview and to record the responses on the tablet that is projected onto the big screen. The respondent should give normal responses with some difficult scenarios.

Ask the rest of the class to follow the interview and raise their hand if they have a question or comment about the interview in front. As a trainer, pause the interview and give immediate feedback if the interviewer could have done better. Consider any aspects of the interview process, including tone of voice, reading speed, way of inquiring, etc. Ask the class for input, e.g., if they spotted the mistake or have any ideas how to do it better. Ask the trainee to repeat the question taking the input on-board. Also highlight things they have done well, so it is clear to the class that this is the way the questionnaire should be administered.

All trainees should record all answers on their own tablet. At the end, their interview files should look the same. Asking the class to submit their interview files after the exercise is a good way to encourage them to follow closely and make sure they record everything.  

### On-site respondents  

Practicing with real respondents on-site is a great way to give trainees more and early exposure to real-world scenarios, while keeping the logistical effort and required training time low. Trainees learn how to apply the theory they learned and how to handle real respondents. Another advantage of this modality is that trainers can observe all or most trainees conducting interviews, which is nearly impossible during field practicing when they are scattered across many homes.

The best timing for an on-site practice is after the questionnaire has been covered completely and be practiced in group practicing, and prior to the first field test.  

Hire a group of respondents to visit the training venue or some other convenient location to be interviewed there. Depending on the number of trainees, around 5-10 respondents are usually enough. They should be similar to respondents in the surveyed population, e.g., cultivate land and keep livestock in agricultural surveys, or have jobs or small businesses in labor force surveys. Make sure to compensate respondents adequately, pay for the transport and refreshments or to invite them to the training lunch should it be provided. 

For the practicing, group trainees into as many groups as you have respondents, ideally not more than 4-6 interviewers per respondent. Each group should conduct a full interview with the respondent. Each trainee should follow on their own device and record answers, and they should take turns in asking the questions, e.g., a few questions or a section at a time. Groups should support each other if individuals fall behind, have questions or make mistakes. Ask groups to submit their interviews after the feedback session to motivate them to get it correct.  

If there is sufficient time, groups can switch respondents and conduct a second or third interview.  

Collect feedback, observe and debrief as described above for [group practice](#group-practice).

### Field practice 

The purpose of field practice is for trainees to get first experience in implementing the questionnaire with real respondents. There is no need to completely mimic field conditions as one does in dress rehearsals. Rather, aim to maximize the number of interviews each trainee can conduct and the number of respondents and scenarios they are exposed to. Prepare field practice well, observe trainees and collect good feedback to make it a success.  

:::: { .warning  data-latex=""}
Field practice often is implemented inefficiently with a lot of time being wasted on logistics that could have been prepared in advance: Teams waiting for transport, community introduction, looking for respondents, etc. It is not uncommon that during a whole day of field practicing, trainees only get to practice for 1 hour or could not practice at all as they did not find any respondent. Prepare well, so trainees can practice how to interview, not how to wait.  
::::

Field practice sessions should be held after the questionnaire has been trained and practiced in class, and before the final dress rehearsal at the end of the training. Often it also makes sense to conduct it prior to sessions on household tracking, receiving rejecting interviews, logistics etc., so that content is broken down more and the field test can focus on the understanding and implementation of the questionnaire only. If the questionnaire is really long, e.g., a LSMS-ISA style questionnaire with long household and agricultural questionnaires, it can be beneficial to conduct more frequent field practices for different parts of the questionnaire. 

Try to be efficient when conducting field practices. If relatively short or only parts of a questionnaire are tested, often half-day field practices are sufficient to give some exposure to trainees and identify sufficient issues to be addressed prior to the next field practice. Since it is usually difficult to conduct class room training after the team has come back from the field, it is often helpful to conduct the field practice in the afternoon, so you can use the morning. 

Visit communities that are not too far from the training venue and large enough to have enough respondents for all trainees. Communities should have similar characteristics to the surveyed communities, but be outside of the sample. Contact or visit the communities the day prior to the field practice, do the community introduction and arrange for respondents at the time of your expected arrival, e.g., with the help of a community leader. Compensating respondents for their participation often helps with their availability and willingness to participate and is totally fine during field practicing. Again, the aim is for trainees to practice the questionnaire as much as possible with respondents. 

Try to minimize other logistical issues that could cause delays. Make sure all tablets are fully charged, synchronized and have battery packs available if needed. Arrange for food and drinks for trainees in the field or ask them to bring it. Make sure your transport arrives on time, knows the way and does not need to stop for petrol. Try to arrive early in communities, as respondents tend to become unavailable during lunch hours. 

Group trainees in pairs of two, trying to take skill levels into account and pairing high performers with low performers. Allocate each pair with a respondent. Agree on a meeting place for trainees to return to and an hour when they need to be back by the latest. Ideally, there is time for more than one interview per pair.  

Similar to the on-site group practices, trainees should take turns interviewing the respondent and both record all answers and submit the interview file at the end of the day. Ask them to write down any issues they experience while they conduct the interview. Working in pairs, one of them can take notes while the other one is interviewing. For each interview, each pair should list at least one question or doubt they had, and something about their interview or respondent that was noteworthy and is useful to share with the class.  

Try to observe as many of the pairs as possible, help and correct where necessary, mark their skills (LINK), and note down any issues you have observed as general feedback for the class. Focus on trainees that are borderline of being selected or that have not been marked yet.  

Collect as much feedback as possible from trainees __before__ you leave the community. It becomes much harder later and the quality of the feedback decreases rapidly. As pairs of trainees arrive back at the meeting place, ask for their written notes, debrief quickly with each pair, clarify any issues they had, and record general feedback for the class. 

:::: { .warning  data-latex=""}
Often trainers assume that the questionnaire is working well and that interviewers are able to administer it correctly because they did not report any issues during feedback sessions. This assumption is wrong. Many issues cannot be identified by interviewers, are forgotten or not reported. Those reported are biased towards trainees' concerns, e.g., they are quick to report something that caused extra effort from their side. Trainers must observe interviews being conducted and compile their own feedback. To receive meaningful feedback from trainees, trainees must note down issues or questions as they experience them and must be debriefed shortly after conducting interviews.
::::

After each field test, hold a general debrief session with the entire class in which you respond to the written feedback from the team, answer any questions, and provide feedback from your observations. This might involve short retraining of concepts or questions that have been ill understood, practicing or role plays. Clarify all issues prior to the next field test. It is normal for quite a few things to go wrong in the first field test and to improve quickly.   

Sometimes, you can debrief to some extent directly in the field in an empty classroom, a community center, the shadow of a big tree, etc. This way interviews are still fresh in everyone's head and there is no need to go back to the classroom after the transport back from the field. If you are required to debrief the same day in the classroom, make sure to leave the field in time and to allow for a long break, as everyone tends to be really tired after field practice, especially after the transport back.  

Design your training schedule such that field practicing days are followed by classroom days, so you can have a detailed debrief session in the classroom with the big screen and all other required facilities.  

## Interviewing techniques 

In addition to understanding the questionnaire content, interviewers must master a range of interviewing techniques that are crucial to collect good quality data. Some examples are:  

- __Introduction and interview request__: Being able to convince respondents to participate in the survey is key to keeping unit non-response error low, particularly in urban areas or other settings with high refusal rates.

- __Interview continuation__: Being able to keep respondents engaged in lengthy interviews and stop them from prematurely ending the interview is important to minimize item non-response and measurement error.

- __Inquiring__: Respondents often do not understand or misinterpret a question, give incomplete answers, respond *"I don't know"* or do not want to disclose some information. Interviewers need to be able to get respondents to answer all questions in a neutral and non-leading manner. 

- __Controlling interviews__: Respondents sometimes digress, give lengthy explanations, or talk about other things. Interviewers need to be able to lead the conversation in a pleasant and courteous manner to maintain the respondent's cooperation. 

Unfortunately, these interviewing techniques are rarely trained. Instead, it is assumed that interviewers automatically know them or will learn them over the course of the survey. In reality, while some interviewers are experienced or naturally good at it, many others struggle or resort to undesirable practices such as making wrong promises to obtain consent or leading responses. This can exacerbate interviewer effects and lead to high levels of measurement error and unit and item non-response. Teaching trainees that are not good a task the skills of those that are mitigates these effects, e.g., see @Groves2001.

Teaching interviewing techniques goes beyond theory. All features of communication are relevant for the interaction between interviewers and respondents, including the choice of words, tone of voice, volume, as well as attitude, facial expressions or gestures. To learn a technique, trainees have to see and hear what they should and shouldn't do, and learn from good examples. To be able to put techniques into use, trainees need to repeatedly practice and receive feedback until they are able to (re)act correctly and quickly. 

Which interviewing techniques are best trained depend on the survey. Interviewers can face different challenges in the field. For example, refusals may be rare in a household survey, but very frequent in an enterprise survey, requiring dedicated training on how to address them. In addition, best practices often are sensitive to the culture and context, e.g., how to inquire if respondents are hesitant to disclose their income. Therefore, the training agenda on interviewing techniques usually needs to be tailored to each survey.

### Identify challenges and responses

To establish which interviewing techniques are most relevant for the survey and should be trained, first compile a list of the key challenges that interviewers are expected to face in the field and need to be prepared for. Focus on those that are most common and have the biggest effect on survey error. Consider any response, concern or action by the respondent or any other situation that can negatively affect data quality if interviewers do not apply the right technique. Examples are:

- respondents refusing an interview stating reasons related to time, etc.
- other members trying to listen to sections to be administered in privacy
- respondents unable to quantify consumption amounts in units
- long and damaging breaks if tablet needs to be restarted
- error messages flagging gross mismatch in harvest quantities, land size and sale prices

Record different ways in which a challenge may manifest itself or how the interviewer can recognize them in the field, using colloquial terms or used by respondents where it applies. As an example, respondents may say *"I am really busy "*, *"I need to leave"* or *"I need to cook/wash/..."* when refusing and stating reasons related to time.

For each challenge, identify good interviewer responses. These can include verbal responses actions or procedures. Often, there is no single response to a challenge that works equally well with all respondents and in all circumstances. Good interviewers often have a repertoire of responses and tailor them to observable features of the respondent or the context. For example, if a respondent refused based on time and appears to be rushed or pre-occupied about something (e.g., fighting children) the best response tends to be to ask for a different moment, e.g., by saying *"I see that now it is difficult. When would be a good moment for me to come back?"*. However, if the respondent refuses because they have to do a chore but seems generally collaborative, it is often good to offer to do the interview while they do their activity. 

For each challenge, also record bad practices or responses that interviewers should avoid, if there are any. As an example, if respondents do not know the quantity consumed of an item, a bad probing practice would be to say *"Was it maybe 1 kg?"*, as this is leading the respondent to answer 1 KG. 

Allocate challenges and responses into separate modules by topic, importance and anticipated time required to train. It is usually good to have at least one module on *Introduction and interview requests*, one on *Inquiring and controlling interviews* and one on *Challenges observed during field testing*. You might need additional modules on key questions or sections, such as *Estimating land size* or *Conducting consumption module*. 

Ideally, challenges and responses should be compiled prior to the training to facilitate planning and make training sessions more productive. Use a combination of any of the following sources to identify challenges and responses:

- experience from previous surveys with similar context, populations and subject
- focus groups with experienced interviewers
- observations and feedback from pre-test or pilots

If you are unable to prepare prior to the training, use challenges and responses observed during field practice sessions or hold short "focus groups" with the class at the beginning of each module. 

See HERE a core set of challenges and responses that are common to many surveys. && NOTE: WOULD IT MAKE SENSE TO COMPILE ONE?

### Train & practice

Schedule modules on interviewing techniques just prior to field practice and final field tests so trainees can apply the techniques soon after. Additionally, you might need to schedule some modules after field practice and field test to practice new situations that came up during field practice or retrain those that do not yet work well. Modules between 45 min and 1.5 hrs. tend to be sufficient to cover one core topic. 

For each module, first train interviewers on what challenges are likely to occur and what the best responses are. Project the list of challenges, categories and good responses on the big screen. Work through each category, identifying together with the class the ways in which challenges may manifest themselves and any tips and tricks for a good response. Also cover bad practices that interviewers should avoid. Ask trainees that are good at a technique (experienced or good interpersonal skills) to demonstrate the best practices in front of class in a role play. Give feedback if necessary and ask the class for input to get consensus and make sure responses are appropriate for culture and context. Try to keep this part short.

After having covered the theory, drill trainees until they are able to respond to a challenge quickly, correctly and in a natural manner. This is best done by asking trainees to simulate the interviewer-respondent interaction in front of class in a role play, providing immediate feedback and letting them repeat if necessary. Depending on class size and skill level, it might be best to divide the class into large groups, each supervised by a trainer. 

To practice, select one trainee to act as interviewer and if needed another one to act as respondent. Usually, it is more useful for the trainer to act as respondent as it allows them to better drive the conversation. Ask the selected trainee to come to the front or just stand up and speak towards the class, which is often faster. Explain the scenario and challenge and ask the trainee to re-enact the interviewer response as if it was a real field situation, speaking loudly so the entire class can hear. Give feedback on what they have done well and what not. Ask the class for input. If the response could be improved, ask the trainee to repeat the response. Collect feedback, correct them and ask them to repeat until the trainee does it well. Practice with as many trainees as possible or until the response generally works well. This can be quite a lot of fun and is a good way of breaking longer theoretical sessions.  

Two examples to illustrate: 

To practice introduction to the survey, select one trainee, ask them to stand up, tell them that they just knocked at a door, a certain type of person opened, that they should introduce themselves and ask for participation. Check that they are giving all necessary information, say nothing wrong, are easy to understand, use the right tone of voice, have good facial expressions and gestures, etc. Collect feedback from the class. Ask the trainee to repeat their introduction until it is correct in content and well presented.

To practice asking for participation, ask a selected trainee to make an introduction and ask for participation as above. Act as respondent who is unwilling to participate, stating one of the challenges discussed in the training, such as _“I am really busy now”_ or _“What do I get out of this?”_. Ask the trainee to respond and convince you to participate. Again, together with the class, check if the trainee's response was quick, correct and natural. Give feedback on possible improvements and let the trainee repeat their response until satisfactory.   

## Expert measurements

As part of some surveys, fieldworkers have to take measurements that require a relatively high level of expertise and thus need special attention during the fieldwork training. Examples include: 

- Anthropometric measurements, i.e., height/length and middle upper arm circumference (MUAC)
- Plot size measurements, soil sample or crop cuttings in agricultural surveys
- Learning outcome assessments in school surveys, measuring reading, writing and math skills
- Medical tests, such as taking blood pressure or measuring hemoglobin levels
- Water quality tests

For these types of measurements to be accurate and precise, fieldworkers usually have to be able to correctly handle specialized equipment and strictly follow testing procedures. For example, in learning outcome assessment tests, interviewers need to simultaneously handle testing booklets, a timer, and the CAPI questionnaire, while guiding a young child and maintaining a neutral testing environment. For water quality tests, interviewers need to handle the water testing equipment and respect the procedures from taking the water sample to testing and reading the results.   

Learning how to implement any of those tasks to sufficiently high standards usually takes several days. Trainees need to learn the theory, extensively practice to gain confidence and be drilled until they are able to take the measurements quickly and always correctly. In addition, for some measurements such as anthropometrics, repeated standardization exercises need to be conducted to streamline trainees' behavior and ensure reliability and validity of the measurements.  

Often, the available training time does not allow for trainees to learn and practice both interviewing and taking the measurements. In those instances, it is best to specialize fieldworker roles, so that some will conduct interviews, while others will focus on taking measurements only. Training for measurement specialists can happen in parallel to the main interviewer training, either from the beginning of fieldwork training (e.g., if a special profile such as trained nurses is required), or of any point during the training, e.g., once a picture emerges which trainees are better suited for which role.

To effectively and efficiently train measurement experts, follow the four steps below.  

### Theory

First, cover the theory including the background and purpose, the functionality and use of the equipment, the detailed steps of the measurement procedure, things to be aware of, avoid, how to answer common questions by respondents, etc. Make this part tangible for trainees by including demonstrations by experts, or videos showing the right use of the tools and the measurement procedures. Test the trainees' level of understanding of the theory using [written tests](#written-tests).

### Practice components

Second, practice as much as possible all components of the measurement process, such as handling testing equipment, taking the sample or reading the measurement. Drill trainees until they can implement all components routinely, quickly and correctly. Being fully familiar with all tools and routines breaks down the overall measurement process and helps trainees to not get overwhelmed when first practicing with a subject or samples.  Since testing subjects (e.g.,, children) are hard to come by and testing kits can have expensive per-unit costs, it is usually also more efficient to practice individual components first. As an example, for anthropometrics, the following components can be practiced:

- __Set-up and handling of equipment__. Scales, height and length boards need to be set up on uneven terrain and be correctly packed, unpacked and carried through communities. Scales might have to be calibrated or calibration checked.

- __Measurement procedures__. For example, depending on the available scales, to take the weight of a young child, one measurement procedure is for the caretaker to step onto the scales first, take Tara, hand the child to the caretaker and take the reading. This process can be easily practiced by trainees e.g., by handing over a backpack.

- __Taking and reading measurements__. Especially for length, measurers only have a moment to take and read the measurement, as children want to move and fight the position in which they are held. Depending on the length board, taking and reading the measurement quickly is far from straightforward and requires a significant amount of practice. You will be surprised by the amount of error that can be eliminated at this stage by repeated practicing. Practice by asking trainees to measure things of known length and gradually decrease the time available per item. Compare individual measurements to the known length. 

### Practice full measurements

Third, once trainees have a good command of all components, bring it all together by practicing to take measurements of actual subjects or real samples. Provide enough and diverse subjects/samples, so trainees can practice repeatedly and are exposed to different scenarios/cases. For example, for anthropometrics, invite children and care takers to the training venue or visit health centers or other institutions with sufficient number of children as testing subjects. Observe trainees and provide immediate feedback to individuals or the entire class. Trouble shoot any issues and re-practice individual components if they can be improved. Practice until trainees can implement the entire measurement procedure correctly and have developed a routine for it.

### Standardize

Fourth, conduct standardization exercises to improve the accuracy and precision of trainees' measurements. In standardization exercises, their measurements are compared against those of an expert, and individual measurements against one another. The exercises serve to identify and eliminate as much as possible any idiosyncratic measurement practices trainees might have causing measurements to deviate from the true value, and as [tests](#standardization-tests) for the final selection of fieldworkers.

Hold standardization exercises towards the end of the training, once trainees can implement the measurement procedures reliably and quickly. Often, it is useful to hold at least two separate exercises, with a break of 1-2 days in between to retrain and practice. 

For a standardization exercise, set up stations with subjects/samples. For example, for anthropometrics this can be children with care takers and sets of scales, length and height board. Ideally, stations have variation in characteristics, e.g., children of different age groups, below and above 2 years, with and without braided hair, etc. The number of stations required depends on the number of trainees. It should be large enough for each trainee to get enough practice and exposure to different scenarios. For larger groups of trainees, it might be best to split trainees into groups and let each group rotate through a subset of stations. Consider the burden on the persons who form part of the station, especially on children for anthropometric measurements.

First, the expert measurer should take two independent measurements at each station and record the values. Their measurements serve as the benchmark against which trainee measurements are compared. If the exercise serves as the test, trainees should not be able to observe this process.

Subsequently, trainees should rotate between all stations and take their own measurements. Use different starting points or directions to speed things up and avoid queues at individual stations. Trainees should record their measurements at each station, together with the station name/ID and their own name. This can be done on paper and later entered into a spreadsheet, or ideally in a short, customized CAPI questionnaire, Google Form or the like. As for the practice, observe trainees and provide immediate feedback. Try to identify why their measurements are deviating, what they need to do to correct it, e.g., stretch the child's legs more to not under-measure their length. Ideally, two independent rounds of measurement should be taken, so that each trainee has measured each station twice. 

The difference between the first and second measurement for each trainee at each station is an indication of the precision/reliability of the measurements. The difference between the measurement taken by trainees at a station and that taken by the expert is indicative of their accuracy/validity. Calculate and interpret the *technical error of measurement (TEM)* to assess the variation of measurements taken by each trainee. For more details, see e.g., [WHO/UNICEF guide on anthropometry in children < 5](https://data.unicef.org/wp-content/uploads/2019/05/Anthropometry-children-under-5-guidance-English_2019.pdf). 


:::tools
**Useful tools**   
- [WHO/UNICEF guide on anthropometry for children < 5](https://data.unicef.org/wp-content/uploads/2019/05/Anthropometry-children-under-5-guidance-English_2019.pdf
){target="_blank"}  
- [Video on anthropometric measurements (French) ](https://www.youtube.com/watch?v=t4dholcfl84)  
- [Video on LandInfo module for soil characterization and identification ](https://landpotential.org/knowledge/landinfo-training/)  
:::


## Pre-interview tasks

Prior to starting an interview, interviewers usually have to take some actions and use tools that need to be covered in the training. Examples are: 

- Identification & tracking of respondents 
- Selection protocols, if there is in-field sampling 
- Identifier system, questionnaire cover, assignment cards, creating interview file 
- Revisiting and replacement protocols 

Usually, it is best to train those pre-interview tasks and tools towards the end of the training, just before interviewers will get to use the tools or practice the tasks in the field. By immediately putting the learnt material into practice, trainees learn the tools and tasks more quickly. At this point during the training, they are also already familiar with the CAPI tool and overall questionnaire content, making things like questionnaire identifiers and revisiting protocols less abstract. Training these items directly at the beginning of the training tends to be less ineffective, since trainees will learn a lot of other material and forget before being able to try it out. Good moments to train pre-interview tasks are usually the days prior to field practice and/or final field tests.  

Most of the tasks are best trained hands-on with concrete examples. Prepare samples of the tools to be used during the training. For example, to train tracking sheets, household identifiers, assignments and how they link, show the tracking sheet for one PSU, together with corresponding assignments, and demonstrate how they relate. Use the PSUs of the final field test to reduce the preparation effort (tracking sheets, assignments, etc. Need to be prepared anyway for final field test), and to make it very tangible for trainees (since they will use them the following day). 

Make sure trainees can practice sufficiently in the training if any of the tasks is complicated, such as e.g., the use of Kish grids for in-field selection of units.  

## Post-interview tasks

In many surveys, interviewers have to conduct certain tasks after completing an interview, such as checking for completion, responding to feedback or inquiries, correcting mistakes, revisiting respondents, etc. These tasks are often underdefined and insufficiently trained, which can result in significant measurement and processing error. For example, interviewers may “fix” interviews by simply changing recorded responses to make issues go away, without actually addressing the underlying problem. Interviewers need to learn what they must and must not do in a dedicated module towards the end of the training.

For surveys conducted in Survey Solutions, one of the main post-interview tasks is to review and respond to rejected interview files. This is used as an example to illustrate how these tasks can be trained. The same principles also apply to other tasks. 

Reviewing and responding to rejected interview files is best trained practically, by looking at actual examples. Ideally, trainees can practice with interview files they have produced themselves. Not only does this make it less theoretical, but it can also show trainees that they actually made some mistakes, what they were and how to prevent them in the future. Use interview files from the [field practice](#) or even better, the [final field test](#final-field-test), as interviews will generally be of better quality and be produced under close to field conditions.

Prior to training this module, trainers (and data monitors if pre-determined or as part of their training) should carefully review submitted interviews and identify issues. Normally,  at the beginning there tends to be at least one per interview. They can make some up for practicing purposes if there are none. They should write comments and feedback as would be written during fieldwork and reject the interviews to the interviewer. Try to do this with at least one file per trainee (or pair of trainees working together during field test). 

During the training, first give a quick general introduction to explain the rejected files tab on the interviewer dashboard, how to open a rejected file, how to read the rejection comment, how to see all comments by the supervisor, how to react to rejected files, respond to comments and resubmit them by marking them as complete and synchronizing.  

Then, project a rejected interview to the main screen and ask the respective trainee/pair to come to the front. They should explain what led to their mistake and what they should do if this occurred in the field. Ask them to respond to the issues and resubmit the file on screen. Ask the class to help and comment. Repeat this with as many files/trainees as possible and useful. Ask all trainees who did not solve their file on the big screen to solve it on their tablet and resubmit them. 

This exercise is also a great way to identify and streamline the rules around responding to rejected files, revisiting respondents, etc. Update the manual if necessary. 
 
## Final field test (often called pilot) {#final-field-test}

At the end of the training, a final field test should be conducted in which all survey questionnaires and protocols are tested under real-field conditions prior to field work. It is an important exercise to:  

- Expose interviewers to field-like conditions and give them the opportunity to practice without affecting the sample 
- Determine if the field team is ready for field work 
- Identify and address any outstanding issues with questionnaire or field procedures  

Some surveys do not conduct a separate [pilot](#pilot) prior to the training and refer to the final field test as pilot. In those cases, the final field test importantly also serves as a reality check for questionnaires and protocols, since they have not been tested in full under field conditions before. 

The final field test should be conducted at the end of the training and prior to the field work. Usually, 2-3 days of final field testing are necessary but also sufficient. If short debriefing/feedback sessions can be held in the late afternoon of each day, they can be on sequential days. If not, schedule debriefing/feedback days between field days. Allow for at least one classroom day after the final field test for an extensive feedback session and to teach the class on how to deal with rejected files, inquiries from HQ or any other post-interview tasks. Additionally, you might need to allow for additional time for admin, rest days or travel to the field location.  

To create conditions as close to the field as possible, the final field test must be conducted with units that are similar to those in the survey sample, but crucially that are not part of the sample. For household surveys, this usually means conducting the final field test in un-selected communities within the survey areas and often requires the team to travel from the training location closer to the field. For surveys part of RCTs, this means practicing within the treatment areas. 

Ideally, locate the final field test such that the entire field team can be supervised and debriefed together in a central location. This ensures that all field workers have received the same input and reduces team effect. Split the final field test into different locations if there is a large variability in the sample that affects questionnaires or protocols. If doing so, try to streamline as much as possible the supervision and feedback given to all groups, e.g., by trainers exchanging notes before providing feedback to their respective group. 

Often it is easiest to select a set of testing PSUs (e.g., communities) during the sample design and have them undergo the same preparation steps as the sampled units, e.g., assignment of IDs, procurement of reference data, add them to the CAPI questionnaire, do community sensitization, etc. For surveys with a separate listing exercise or panel surveys, conduct the dress rehearsal for all stages using the same units and keep the data, so you can properly prepare and test each stage of the survey. It can be very laborious and cumbersome to prepare separate data.   

One important aspect of the final field test is for field workers to practice the selection, identification and tracking of survey units such as households, convincing respondents to participate and to learn how to make appointments and to manage time. Do not pre-arrange respondents as one would do during field practice. Equip interviewers with the same assignments or tracking sheet format they would receive during field work. If you do not have lists or names for the rehearsal units (e.g., you have the household names for sampled communities, but not for practicing communities), send someone to the community prior to compile lists that you can use to produce the assignments/tracking lists.

Allocate interviewers to their expected field teams and let the supervisors assume their management role, including the assignment of cases to interviewers. For the final field test, it is often beneficial for interviewers to conduct interviews in pairs. This reduces the number of cases required in any of the visited communities, increases the probability of finding available respondents and allows interviewers to help one another. Each pair can conduct multiple interviews per day and take turns in administering the questionnaire. As in the field tests, both interviewers should record all answers on their own tablet and submit the interview in the end.  

For the final field test, you might need to relax replacement protocols and add additional replacement units, so interviewers can practice conducting some interviews even if non–response is high. 

Make sure field teams arrive early in the communities, so that interviewers have enough time to locate cases and conduct interviews before respondents start cooking/having lunch and become unavailable. As for the field practice, make all necessary logistical arrangements to prevent delays or hungry/thirsty field workers in the field.  

Collect feedback and debrief as described for [field practice](#field-practice). Ask all interviewers to submit their interviews at the end of the day. Use the data to finalize your data system and quality control system, e.g., by updating the data checks. Review submitted interviews using the standard processes of the quality control system. In addition, visually review as many cases as possible and compile feedback for interviewers and the quality assurance team.  

The data collected during dress rehearsal is a great way to learn and practice receiving feedback with the team, see chapter feedback.

## Supervisor training

A short training for supervisors is required to prepare them for their role.  It should be held outside of the hours of the main fieldworker training, so supervisors can attend both and are also fully trained as interviewers. If supervisors are pre-determined, a short supervisor training can be held prior to the start of the main fieldworker training that covers all tasks that do not built upon the main fieldworker training, such as administrative and logistical matters.  

If supervisors are selected from the pool of trainees, try to select and train all necessary content prior to the final field test, so supervisors can assume and practice their role during the final field test and be observed by trainers. Depending on the tasks their role entails, 1-2 days of supervisor training tend to be sufficient. Use the afternoons, evenings or the hours of any modules in the main fieldworker training that are not relevant for supervisors. If supervisors are required to conduct separate interviews (e.g., community), significantly more time of training is required. 

Prior to the training, make sure supervisor tasks are clearly defined and written up in the supervisor manual.<!-- ??ADD LINK -->

The content of the supervisor training tends to be very survey dependent. It can include topics such as: 

- PSU tracking and community introduction
- Assignment of units to interviewers and workload management 
- Check health of interviews (any unanswered questions, errors, comments?) 
- Checking PSU completion  
- Observation of interviews, conducting back-checks  
- Administrative and logistical matters, such as handling of finances, accommodation, transport etc.  

Use the final field test to train tasks that are best learnt by doing. This tends to significantly reduce the number of issues experienced during the beginning of field work, such as incomplete submitted interviews or incomplete PSUs. For example, to train supervisors on checking the health of completed interviews, review with all supervisors the interviews submitted from the final field test. One supervisor can review and run through the check-list for a few files, with the rest of the supervisors observing and providing feedback, before another one takes over. To look at the PSU completion, review with all supervisors the completion status of each of the final field test PSUs.  

It is recommended that in-depth data monitoring tasks beyond checking completion and health of the interviews are conducted by central data monitors to reduce data monitoring effect. Should supervisors nonetheless need to assume (parts of) their role, they also need to be trained as data monitors. See details in the following chapter.   

## Data monitor training

Data monitor training is an important component of quality assurance in surveys. It serves to:

- __Prepare data monitors for their role__, so they can correctly identify issues in the received data, conduct back checking exercises, take the right actions and provide meaningful feedback. 

- __Homogenize behavior of data monitors__ as much as possible, to ensure all field teams receive the same level of scrutiny and to reduce the [data monitor effect](#impacterror).

- __Improve data monitoring process__. The issues occurring in a survey and the actions required by data monitors tend to differ from survey to survey. Extensive practice using actual cases from the survey context is a great way to refine the tools, processes and tasks for data monitors, improving the overall review process. 

The data monitor training is best held after the final field test, once a good number of interviews created under near-field conditions are available for practicing. Importantly, this also allows data monitors to attend the main fieldworker training in full, so they can have a solid understanding of the content and the activities they will be monitoring. If data monitors are selected as part of the fieldworker selection, the training can also only start after it. Data monitors must be able to start their work once fieldwork has started and the first cases are available to be reviewed, typically on day 2 of fieldwork. It is important that fieldworkers receive timely feedback, especially for the first few cases, and that there are no backlogs of un-reviewed cases building up.

In most cases, a total of 2-3 days of data monitoring training is sufficient, if you supervise and work closely with them for the first few days of fieldwork. The training can be held in the afternoons or evenings of the last few days of fieldwork training, or during sessions that are not relevant for data monitors, such as administrative matters for fieldworkers. If data monitors stay at a central location, you can also train on the day the fieldteams travel to the field and the first day(s) of fieldwork before cases become available to be reviewed. 

Prior to the training, clearly define data monitors' tasks, procedures they need to follow, check list, etc. and write everything in a short manual focusing on the essentials (see an example [here](resources/IFAD package data monitor manual.pdf){target="_blank"}). Add to the manual a list of scenarios data monitors will face frequently and the actions they should take. For example, `If GPS question is missing -> trouble shoot tablet's location setup with interviewer. If not working -> report to survey management. If working -> Check if they can revisit household. If yes -> reject interview. If no -> comment in interview file, explaining reasons`. Alternatively, list common issues and responses in a Google sheet or similar that is made available to data monitors and that they can refer to. Add to this list and refine responses throughout the training and beginning of fieldwork.  

At the beginning of the data monitor training, cover all theory and components of the tasks/procedures. While the details depend on the survey, this may include:

- general overview of the quality assurance process and their role  
- how to use any tool or software, such as Survey Solutions Supervisor interface, dashboards, etc.  
- how to check completion or use field check tables, etc.   
- how to review cases, what to check for, how to interpret error messages, etc.  
- how to back check cases, conduct re-interviews, conduct audio audits, etc.    
- how to provide feedback to field teams and survey management  

Keep presentations to a minimum and train hands-on as much as possible. For example, while explaining how to review an interview file in Survey Solutions, data monitors can follow on their own devices, so they can immediately try out and learn how to find comments, unanswered questions, approve/reject, etc. Provide copies of the material that data monitors need to work with, such as interview cases, back check questionnaires, reports, etc. 

As a next step, practice with data monitors so they can learn and internalize their tasks. This should be done using real interviews that are not part of the sample, such as the interviews from field practices, or ideally of the final field test, as they more closely resemble the data from actual fieldwork. Using actual interviews makes the exercise more tangible for data monitors, as they can see the type of issues that are expected to occur and learn how to react to them. Use the practicing to update and refine the review process, i.e., the list of key issues data monitors need to check, the type of feedback they should provide and the actions they need to take. 

Practicing should be done such that data monitors' behavior starts to be harmonized.  An easy to prepare and very effective way to practice is to first run through a couple of cases together. Project the necessary material on the big screen in front, and ask one data monitor to come to the front and work through the case on the big screen. Ask the others to observe and provide input. Provide immediate input if they have done something wrong, missed something, but also if they have done things correctly. Discuss any points of doubt and update procedures if necessary. Repeat this with other cases and other data monitors until all data monitors have worked through several cases.

Also effective, but more demanding in the preparation, is to provide the same cases to all data monitors, ask them to work through them and to compare results afterwards. As an example, provide each data monitor with the audio recording of the same interview and an auditing form, ask them to listen to the interview and fill in the form. Once complete, compare the forms in the group, discuss any discrepancies and reiterate important points.

Practice until data monitors are able to correctly implement all tasks, until you have run out of practicing cases, or until field work has started. 

Once the first data is received from the field, it is important that data monitors shift to work on the actual cases from the sample. Often, however, at this stage data monitors are not fully ready to implement all tasks in a harmonized way. Therefore, it is paramount that data monitors are closely supervised  by one of the trainers during the first few days and that good communication channels are put into place. 

If working from a central location, data monitors should ideally work from the same room so they can quickly exchange thoughts and one of the trainers can rotate, observe and provide feedback if necessary. If working from different locations, a common group chat or channel on WhatsApp, Teams, etc. should be set up to facilitate quick and easy communication and ensure all data monitors receive the same information. Data monitors should immediately communicate on the common channel if they have any doubts about a case or scenario or if they have made any noteworthy observations. Update the manual, tools or processes if necessary. 

Conduct spot checks of some of the cases that have been worked through by data monitors. Hold regular debriefs with all data monitors to provide feedback.  
